// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// ChronicleNamespace provides methods for the chronicle engine.
//
// Structured audit event engine
type ChronicleNamespace struct {
	transport Transport
	engine    string
}

func newChronicleNamespace(transport Transport, engine string) *ChronicleNamespace {
	return &ChronicleNamespace{transport: transport, engine: engine}
}

// Actors executes ACTORS — Active actors in time window
func (ns *ChronicleNamespace) Actors(ctx context.Context, opts *ChronicleActorsOptions) (*ChronicleActorsResponse, error) {
	args := []string{"ACTORS"}
	if opts != nil {
		if opts.FilterArgs != nil {
			args = append(args, "FILTER_ARGS", fmt.Sprint(*opts.FilterArgs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleActorsResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Auth executes AUTH — Authenticate this connection
func (ns *ChronicleNamespace) Auth(ctx context.Context, token string) (*ChronicleAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Count executes COUNT — Count events matching filter predicates
func (ns *ChronicleNamespace) Count(ctx context.Context, opts *ChronicleCountOptions) (*ChronicleCountResponse, error) {
	args := []string{"COUNT"}
	if opts != nil {
		if opts.FilterArgs != nil {
			args = append(args, "FILTER_ARGS", fmt.Sprint(*opts.FilterArgs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleCountResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Errors executes ERRORS — Error rates by action
func (ns *ChronicleNamespace) Errors(ctx context.Context, opts *ChronicleErrorsOptions) (*ChronicleErrorsResponse, error) {
	args := []string{"ERRORS"}
	if opts != nil {
		if opts.FilterArgs != nil {
			args = append(args, "FILTER_ARGS", fmt.Sprint(*opts.FilterArgs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleErrorsResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Health check
func (ns *ChronicleNamespace) Health(ctx context.Context) (*ChronicleHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Hotspots executes HOTSPOTS — Top actors by event volume
func (ns *ChronicleNamespace) Hotspots(ctx context.Context, opts *ChronicleHotspotsOptions) (*ChronicleHotspotsResponse, error) {
	args := []string{"HOTSPOTS"}
	if opts != nil {
		if opts.FilterArgs != nil {
			args = append(args, "FILTER_ARGS", fmt.Sprint(*opts.FilterArgs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleHotspotsResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ingest executes INGEST — Ingest a single structured audit event
func (ns *ChronicleNamespace) Ingest(ctx context.Context, event_json any) (*ChronicleIngestResponse, error) {
	args := []string{"INGEST"}
	event_jsonJSON, err := json.Marshal(event_json)
	if err != nil {
		return nil, fmt.Errorf("marshal event_json: %w", err)
	}
	args = append(args, string(event_jsonJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleIngestResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// IngestBatch executes INGEST_BATCH — Ingest multiple events in a single call
func (ns *ChronicleNamespace) IngestBatch(ctx context.Context, events_json any) (*ChronicleIngestBatchResponse, error) {
	args := []string{"INGEST_BATCH"}
	events_jsonJSON, err := json.Marshal(events_json)
	if err != nil {
		return nil, fmt.Errorf("marshal events_json: %w", err)
	}
	args = append(args, string(events_jsonJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleIngestBatchResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Keepalive
func (ns *ChronicleNamespace) Ping(ctx context.Context) error {
	args := []string{"PING"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Query executes QUERY — Query events with filter predicates
func (ns *ChronicleNamespace) Query(ctx context.Context, opts *ChronicleQueryOptions) (*ChronicleQueryResponse, error) {
	args := []string{"QUERY"}
	if opts != nil {
		if opts.FilterArgs != nil {
			args = append(args, "FILTER_ARGS", fmt.Sprint(*opts.FilterArgs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ChronicleQueryResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
