// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// CipherNamespace provides methods for the cipher engine.
//
// Encryption-as-a-service
type CipherNamespace struct {
	transport Transport
	engine    string
}

func newCipherNamespace(transport Transport, engine string) *CipherNamespace {
	return &CipherNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate the connection
func (ns *CipherNamespace) Auth(ctx context.Context, token string) (*CipherAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List all supported commands
func (ns *CipherNamespace) CommandList(ctx context.Context) (*CipherCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Decrypt executes DECRYPT — Decrypt ciphertext using the embedded key version
func (ns *CipherNamespace) Decrypt(ctx context.Context, keyring string, ciphertext string, opts *CipherDecryptOptions) (*CipherDecryptResponse, error) {
	args := []string{"DECRYPT"}
	args = append(args, keyring)
	args = append(args, ciphertext)
	if opts != nil {
		if opts.Context != nil {
			args = append(args, "CONTEXT", fmt.Sprint(*opts.Context))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherDecryptResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Encrypt executes ENCRYPT — Encrypt plaintext with the active key version
func (ns *CipherNamespace) Encrypt(ctx context.Context, keyring string, plaintext string, opts *CipherEncryptOptions) (*CipherEncryptResponse, error) {
	args := []string{"ENCRYPT"}
	args = append(args, keyring)
	args = append(args, plaintext)
	if opts != nil {
		if opts.Context != nil {
			args = append(args, "CONTEXT", fmt.Sprint(*opts.Context))
		}
		if opts.KeyVersion != nil {
			args = append(args, "KEY_VERSION", fmt.Sprint(*opts.KeyVersion))
		}
		if opts.Convergent {
			args = append(args, "CONVERGENT")
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherEncryptResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// GenerateDataKey executes GENERATE_DATA_KEY — Generate a data encryption key (envelope encryption pattern)
func (ns *CipherNamespace) GenerateDataKey(ctx context.Context, keyring string, opts *CipherGenerateDataKeyOptions) (*CipherGenerateDataKeyResponse, error) {
	args := []string{"GENERATE_DATA_KEY"}
	args = append(args, keyring)
	if opts != nil {
		if opts.Bits != nil {
			args = append(args, "BITS", fmt.Sprint(*opts.Bits))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherGenerateDataKeyResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Check server health
func (ns *CipherNamespace) Health(ctx context.Context) (*CipherHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// KeyInfo executes KEY_INFO — Get keyring metadata and key version information
func (ns *CipherNamespace) KeyInfo(ctx context.Context, keyring string) (*CipherKeyInfoResponse, error) {
	args := []string{"KEY_INFO"}
	args = append(args, keyring)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherKeyInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// KeyringCreate executes KEYRING CREATE — Create a new keyring with its first active key
func (ns *CipherNamespace) KeyringCreate(ctx context.Context, name string, algorithm string, opts *CipherKeyringCreateOptions) (*CipherKeyringCreateResponse, error) {
	args := []string{"KEYRING", "CREATE"}
	args = append(args, name)
	args = append(args, fmt.Sprint(algorithm))
	if opts != nil {
		if opts.RotationDays != nil {
			args = append(args, "ROTATION_DAYS", fmt.Sprint(*opts.RotationDays))
		}
		if opts.DrainDays != nil {
			args = append(args, "DRAIN_DAYS", fmt.Sprint(*opts.DrainDays))
		}
		if opts.Convergent {
			args = append(args, "CONVERGENT")
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherKeyringCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// KeyringList executes KEYRING LIST — List all keyring names
func (ns *CipherNamespace) KeyringList(ctx context.Context) (*CipherKeyringListResponse, error) {
	args := []string{"KEYRING", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherKeyringListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Simple connectivity check — returns PONG
func (ns *CipherNamespace) Ping(ctx context.Context) (*CipherPingResponse, error) {
	args := []string{"PING"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherPingResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Rewrap executes REWRAP — Re-encrypt ciphertext with the current active key version
func (ns *CipherNamespace) Rewrap(ctx context.Context, keyring string, ciphertext string, opts *CipherRewrapOptions) (*CipherRewrapResponse, error) {
	args := []string{"REWRAP"}
	args = append(args, keyring)
	args = append(args, ciphertext)
	if opts != nil {
		if opts.Context != nil {
			args = append(args, "CONTEXT", fmt.Sprint(*opts.Context))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherRewrapResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Rotate executes ROTATE — Rotate the keyring to a new key version
func (ns *CipherNamespace) Rotate(ctx context.Context, keyring string, opts *CipherRotateOptions) (*CipherRotateResponse, error) {
	args := []string{"ROTATE"}
	args = append(args, keyring)
	if opts != nil {
		if opts.Force {
			args = append(args, "FORCE")
		}
		if opts.Dryrun {
			args = append(args, "DRYRUN")
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherRotateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Sign executes SIGN — Create a detached signature
func (ns *CipherNamespace) Sign(ctx context.Context, keyring string, data string) (*CipherSignResponse, error) {
	args := []string{"SIGN"}
	args = append(args, keyring)
	args = append(args, data)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherSignResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// VerifySignature executes VERIFY_SIGNATURE — Verify a detached signature
func (ns *CipherNamespace) VerifySignature(ctx context.Context, keyring string, data string, signature string) (*CipherVerifySignatureResponse, error) {
	args := []string{"VERIFY_SIGNATURE"}
	args = append(args, keyring)
	args = append(args, data)
	args = append(args, signature)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CipherVerifySignatureResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
