// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"fmt"
	"strings"
)

// Options configures the ShrouDB client.
type Options struct {
	// Moat is the Moat gateway URL. When set, engines without a dedicated
	// URI are routed through this gateway.
	//
	// HTTP:  https://moat.example.com
	// RESP3: shroudb-moat://token@host:8201
	Moat string

	// Token is the bearer token for Moat HTTP authentication.
	Token string

	// Shroudb is the direct shroudb URI (overrides Moat for this engine).
	Shroudb string
	// Cipher is the direct cipher URI (overrides Moat for this engine).
	Cipher string
	// Sigil is the direct sigil URI (overrides Moat for this engine).
	Sigil string
	// Veil is the direct veil URI (overrides Moat for this engine).
	Veil string
	// Sentry is the direct sentry URI (overrides Moat for this engine).
	Sentry string
	// Forge is the direct forge URI (overrides Moat for this engine).
	Forge string
	// Keep is the direct keep URI (overrides Moat for this engine).
	Keep string
	// Courier is the direct courier URI (overrides Moat for this engine).
	Courier string
	// Chronicle is the direct chronicle URI (overrides Moat for this engine).
	Chronicle string
	// Stash is the direct stash URI (overrides Moat for this engine).
	Stash string
	// Scroll is the direct scroll URI (overrides Moat for this engine).
	Scroll string
}

// ShrouDB is the unified client for all ShrouDB engines.
//
// Provides namespaced access to all engines. Each engine is accessible
// as a field (e.g., db.Cipher.Encrypt(ctx, ...)).
//
// Supply a Moat URL to route all engines through a Moat gateway,
// or individual engine URIs for direct connections.
type ShrouDB struct {
	Shroudb *ShroudbNamespace
	Cipher *CipherNamespace
	Sigil *SigilNamespace
	Veil *VeilNamespace
	Sentry *SentryNamespace
	Forge *ForgeNamespace
	Keep *KeepNamespace
	Courier *CourierNamespace
	Chronicle *ChronicleNamespace
	Stash *StashNamespace
	Scroll *ScrollNamespace

	transports []Transport
}

// New creates a new ShrouDB client with the given options.
func New(opts Options) (*ShrouDB, error) {
	db := &ShrouDB{}

	var defaultTransport Transport
	if opts.Moat != "" {
		if strings.HasPrefix(opts.Moat, "http://") || strings.HasPrefix(opts.Moat, "https://") {
			prefixes := map[string]string{
				"shroudb": "/v1/shroudb",
				"cipher": "/v1/cipher",
				"sigil": "/v1/sigil",
				"veil": "/v1/veil",
				"sentry": "/v1/sentry",
				"forge": "/v1/forge",
				"keep": "/v1/keep",
				"courier": "/v1/courier",
				"chronicle": "/v1/chronicle",
				"stash": "/v1/stash",
				"scroll": "/v1/scroll",
			}
			defaultTransport = NewHttpTransport(opts.Moat, opts.Token, prefixes)
		} else {
			t, err := NewMoatResp3Transport(opts.Moat)
			if err != nil {
				return nil, fmt.Errorf("moat transport: %w", err)
			}
			defaultTransport = t
		}
		db.transports = append(db.transports, defaultTransport)
	}

	if opts.Shroudb != "" {
		t, err := NewResp3Transport(opts.Shroudb)
		if err != nil {
			return nil, fmt.Errorf("shroudb transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Shroudb = newShroudbNamespace(t, "shroudb")
	} else if defaultTransport != nil {
		db.Shroudb = newShroudbNamespace(defaultTransport, "shroudb")
	}

	if opts.Cipher != "" {
		t, err := NewResp3Transport(opts.Cipher)
		if err != nil {
			return nil, fmt.Errorf("cipher transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Cipher = newCipherNamespace(t, "cipher")
	} else if defaultTransport != nil {
		db.Cipher = newCipherNamespace(defaultTransport, "cipher")
	}

	if opts.Sigil != "" {
		t, err := NewResp3Transport(opts.Sigil)
		if err != nil {
			return nil, fmt.Errorf("sigil transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Sigil = newSigilNamespace(t, "sigil")
	} else if defaultTransport != nil {
		db.Sigil = newSigilNamespace(defaultTransport, "sigil")
	}

	if opts.Veil != "" {
		t, err := NewResp3Transport(opts.Veil)
		if err != nil {
			return nil, fmt.Errorf("veil transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Veil = newVeilNamespace(t, "veil")
	} else if defaultTransport != nil {
		db.Veil = newVeilNamespace(defaultTransport, "veil")
	}

	if opts.Sentry != "" {
		t, err := NewResp3Transport(opts.Sentry)
		if err != nil {
			return nil, fmt.Errorf("sentry transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Sentry = newSentryNamespace(t, "sentry")
	} else if defaultTransport != nil {
		db.Sentry = newSentryNamespace(defaultTransport, "sentry")
	}

	if opts.Forge != "" {
		t, err := NewResp3Transport(opts.Forge)
		if err != nil {
			return nil, fmt.Errorf("forge transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Forge = newForgeNamespace(t, "forge")
	} else if defaultTransport != nil {
		db.Forge = newForgeNamespace(defaultTransport, "forge")
	}

	if opts.Keep != "" {
		t, err := NewResp3Transport(opts.Keep)
		if err != nil {
			return nil, fmt.Errorf("keep transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Keep = newKeepNamespace(t, "keep")
	} else if defaultTransport != nil {
		db.Keep = newKeepNamespace(defaultTransport, "keep")
	}

	if opts.Courier != "" {
		t, err := NewResp3Transport(opts.Courier)
		if err != nil {
			return nil, fmt.Errorf("courier transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Courier = newCourierNamespace(t, "courier")
	} else if defaultTransport != nil {
		db.Courier = newCourierNamespace(defaultTransport, "courier")
	}

	if opts.Chronicle != "" {
		t, err := NewResp3Transport(opts.Chronicle)
		if err != nil {
			return nil, fmt.Errorf("chronicle transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Chronicle = newChronicleNamespace(t, "chronicle")
	} else if defaultTransport != nil {
		db.Chronicle = newChronicleNamespace(defaultTransport, "chronicle")
	}

	if opts.Stash != "" {
		t, err := NewResp3Transport(opts.Stash)
		if err != nil {
			return nil, fmt.Errorf("stash transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Stash = newStashNamespace(t, "stash")
	} else if defaultTransport != nil {
		db.Stash = newStashNamespace(defaultTransport, "stash")
	}

	if opts.Scroll != "" {
		t, err := NewResp3Transport(opts.Scroll)
		if err != nil {
			return nil, fmt.Errorf("scroll transport: %w", err)
		}
		db.transports = append(db.transports, t)
		db.Scroll = newScrollNamespace(t, "scroll")
	} else if defaultTransport != nil {
		db.Scroll = newScrollNamespace(defaultTransport, "scroll")
	}

	return db, nil
}

// Close releases all connections held by the client.
func (db *ShrouDB) Close() error {
	var firstErr error
	for _, t := range db.transports {
		if err := t.Close(); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}
