// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
)

// CourierNamespace provides methods for the courier engine.
//
// Just-in-time decryption delivery engine
type CourierNamespace struct {
	transport Transport
	engine    string
}

func newCourierNamespace(transport Transport, engine string) *CourierNamespace {
	return &CourierNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate the connection with a token
func (ns *CourierNamespace) Auth(ctx context.Context, token string) (*CourierAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ChannelCreate executes CHANNEL CREATE — Create a delivery channel
func (ns *CourierNamespace) ChannelCreate(ctx context.Context, name string, typ string, config_json string) (*CourierChannelCreateResponse, error) {
	args := []string{"CHANNEL", "CREATE"}
	args = append(args, fmt.Sprint(name))
	args = append(args, fmt.Sprint(typ))
	args = append(args, fmt.Sprint(config_json))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierChannelCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ChannelDelete executes CHANNEL DELETE — Delete a channel
func (ns *CourierNamespace) ChannelDelete(ctx context.Context, name string) (*CourierChannelDeleteResponse, error) {
	args := []string{"CHANNEL", "DELETE"}
	args = append(args, fmt.Sprint(name))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierChannelDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ChannelGet executes CHANNEL GET — Get channel configuration
func (ns *CourierNamespace) ChannelGet(ctx context.Context, name string) (*CourierChannelGetResponse, error) {
	args := []string{"CHANNEL", "GET"}
	args = append(args, fmt.Sprint(name))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierChannelGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ChannelList executes CHANNEL LIST — List all channels
func (ns *CourierNamespace) ChannelList(ctx context.Context) (*CourierChannelListResponse, error) {
	args := []string{"CHANNEL", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierChannelListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List available commands
func (ns *CourierNamespace) CommandList(ctx context.Context) (*CourierCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Deliver executes DELIVER — Decrypt recipient and deliver a message
func (ns *CourierNamespace) Deliver(ctx context.Context, jsonData string) (*CourierDeliverResponse, error) {
	args := []string{"DELIVER"}
	args = append(args, fmt.Sprint(jsonData))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierDeliverResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Server health check
func (ns *CourierNamespace) Health(ctx context.Context) (*CourierHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// NotifyEvent executes NOTIFY_EVENT — Trigger a notification on a pre-configured channel (e.g. rotation/expiry alerts)
func (ns *CourierNamespace) NotifyEvent(ctx context.Context, channel string, subject string, body string) (*CourierNotifyEventResponse, error) {
	args := []string{"NOTIFY_EVENT"}
	args = append(args, fmt.Sprint(channel))
	args = append(args, subject)
	args = append(args, body)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp CourierNotifyEventResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Connectivity check
func (ns *CourierNamespace) Ping(ctx context.Context) error {
	args := []string{"PING"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}
