// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import "fmt"

// ShrouDBError represents an error returned by a ShrouDB engine.
type ShrouDBError struct {
	// Code is the error code from the server (e.g. "NOTFOUND", "DENIED").
	Code    string
	// Message is the human-readable error detail.
	Message string
}

// Error implements the error interface.
func (e *ShrouDBError) Error() string {
	return fmt.Sprintf("%s %s", e.Code, e.Message)
}

// IsCode returns true if err is a ShrouDBError with the given code.
func IsCode(err error, code string) bool {
	if e, ok := err.(*ShrouDBError); ok {
		return e.Code == code
	}
	return false
}

// Known ShrouDB error codes.
const (
	// ErrACCOUNT_LOCKED — Account locked after too many failed attempts. Only emitted for credential fields whose CredentialPolicy carries a non-null LockoutPolicy.
	ErrACCOUNT_LOCKED = "ACCOUNT_LOCKED"
	// ErrADAPTER — Delivery adapter failure
	ErrADAPTER = "ADAPTER"
	// ErrAUTH_REQUIRED — Authentication required
	ErrAUTH_REQUIRED = "AUTH_REQUIRED"
	// ErrBADARG — Missing or invalid argument
	ErrBADARG = "BADARG"
	// ErrBAD_ARG — Missing or malformed command argument
	ErrBAD_ARG = "BAD_ARG"
	// ErrCAPABILITY — Required engine capability is not configured (e.g. Cipher)
	ErrCAPABILITY = "CAPABILITY"
	// ErrCAPABILITY_MISSING — Required engine capability not available (e.g., Cipher for PII fields)
	ErrCAPABILITY_MISSING = "CAPABILITY_MISSING"
	// ErrCIPHER_UNAVAILABLE — Cipher engine not available for envelope encryption
	ErrCIPHER_UNAVAILABLE = "CIPHER_UNAVAILABLE"
	// ErrCLIENT_ENCRYPTED — Cannot fingerprint a client-encrypted blob (client manages encryption)
	ErrCLIENT_ENCRYPTED = "CLIENT_ENCRYPTED"
	// ErrCONFLICT — Reader group already exists, or CAS retry budget exhausted on group cursor advancement
	ErrCONFLICT = "CONFLICT"
	// ErrCRYPTO — Encryption or decryption failed
	ErrCRYPTO = "CRYPTO"
	// ErrDECRYPT — Cipher decryption failed
	ErrDECRYPT = "DECRYPT"
	// ErrDELETED — Secret has been soft-deleted
	ErrDELETED = "DELETED"
	// ErrDENIED — Authentication required or insufficient permissions
	ErrDENIED = "DENIED"
	// ErrDISABLED — Keyring is disabled
	ErrDISABLED = "DISABLED"
	// ErrDUPLICATE_VIEWER — Viewer already has a fingerprinted copy of this blob
	ErrDUPLICATE_VIEWER = "DUPLICATE_VIEWER"
	// ErrENCRYPTION — Encryption or decryption failed
	ErrENCRYPTION = "ENCRYPTION"
	// ErrENTITY_EXISTS — Entity already exists
	ErrENTITY_EXISTS = "ENTITY_EXISTS"
	// ErrENTITY_NOT_FOUND — Entity does not exist
	ErrENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
	// ErrEXISTS — Keyring already exists
	ErrEXISTS = "EXISTS"
	// ErrIMPORT_FAILED — Password import failed (invalid hash format)
	ErrIMPORT_FAILED = "IMPORT_FAILED"
	// ErrINTERNAL — Unexpected server error
	ErrINTERNAL = "INTERNAL"
	// ErrINVALID_ARGUMENT — Invalid argument
	ErrINVALID_ARGUMENT = "INVALID_ARGUMENT"
	// ErrINVALID_FIELD — Field value is invalid or field cannot be updated via this path
	ErrINVALID_FIELD = "INVALID_FIELD"
	// ErrINVALID_TOKEN — Token is invalid, expired, or revoked
	ErrINVALID_TOKEN = "INVALID_TOKEN"
	// ErrMISSING_FIELD — Required field missing from request
	ErrMISSING_FIELD = "MISSING_FIELD"
	// ErrNAMESPACE_EXISTS — Namespace already exists
	ErrNAMESPACE_EXISTS = "NAMESPACE_EXISTS"
	// ErrNAMESPACE_NOT_EMPTY — Namespace is not empty (use FORCE to override)
	ErrNAMESPACE_NOT_EMPTY = "NAMESPACE_NOT_EMPTY"
	// ErrNAMESPACE_NOT_FOUND — Namespace does not exist
	ErrNAMESPACE_NOT_FOUND = "NAMESPACE_NOT_FOUND"
	// ErrNOKEY — No active signing key available
	ErrNOKEY = "NOKEY"
	// ErrNOTFOUND — Keyring or key version not found
	ErrNOTFOUND = "NOTFOUND"
	// ErrNOT_AUTHENTICATED — No auth token provided on this connection
	ErrNOT_AUTHENTICATED = "NOT_AUTHENTICATED"
	// ErrNOT_FOUND — Key or resource does not exist
	ErrNOT_FOUND = "NOT_FOUND"
	// ErrNOT_READY — Server is not in READY state
	ErrNOT_READY = "NOT_READY"
	// ErrOBJECT_STORE — S3 object store operation failed
	ErrOBJECT_STORE = "OBJECT_STORE"
	// ErrPIPELINE_ABORTED — Pipeline command failed, all commands rolled back
	ErrPIPELINE_ABORTED = "PIPELINE_ABORTED"
	// ErrPOLICY — Operation denied by keyring policy
	ErrPOLICY = "POLICY"
	// ErrPREFIX_TOO_LARGE — A DELPREFIX call matched more keys than the configured per-call cap. No keys were deleted. Caller should refine the prefix and retry. Wire format: `PREFIXTOOLARGE matched=<n> limit=<m>`.
	ErrPREFIX_TOO_LARGE = "PREFIX_TOO_LARGE"
	// ErrRETIRED — Key version is retired — use REWRAP
	ErrRETIRED = "RETIRED"
	// ErrREVOKED — Blob has been soft-revoked
	ErrREVOKED = "REVOKED"
	// ErrSCHEMA_EXISTS — Schema already exists
	ErrSCHEMA_EXISTS = "SCHEMA_EXISTS"
	// ErrSCHEMA_NOT_FOUND — Schema does not exist
	ErrSCHEMA_NOT_FOUND = "SCHEMA_NOT_FOUND"
	// ErrSCHEMA_VALIDATION — Schema definition is invalid
	ErrSCHEMA_VALIDATION = "SCHEMA_VALIDATION"
	// ErrSHREDDED — Blob has been crypto-shredded (unrecoverable)
	ErrSHREDDED = "SHREDDED"
	// ErrSIGNING — Failed to sign decision
	ErrSIGNING = "SIGNING"
	// ErrSTORAGE — Backend storage error
	ErrSTORAGE = "STORAGE"
	// ErrSTORE — ShrouDB Store (metadata) operation failed
	ErrSTORE = "STORE"
	// ErrTOKEN_REUSE — Refresh token reuse detected — entire family revoked
	ErrTOKEN_REUSE = "TOKEN_REUSE"
	// ErrVALIDATION_FAILED — Metadata validation failed against namespace schema
	ErrVALIDATION_FAILED = "VALIDATION_FAILED"
	// ErrVERIFICATION_FAILED — Credential verification failed (wrong password)
	ErrVERIFICATION_FAILED = "VERIFICATION_FAILED"
	// ErrVERSION_CONFLICT — Compare-and-swap precondition failed. The error carries the actual current version so clients can retry without re-reading. Wire format: `VERSIONCONFLICT current=<n>`.
	ErrVERSION_CONFLICT = "VERSION_CONFLICT"
	// ErrVERSION_NOTFOUND — Requested version does not exist
	ErrVERSION_NOTFOUND = "VERSION_NOTFOUND"
	// ErrVERSION_NOT_FOUND — Requested version does not exist
	ErrVERSION_NOT_FOUND = "VERSION_NOT_FOUND"
	// ErrWRONGTYPE — Operation not supported for this keyring type
	ErrWRONGTYPE = "WRONGTYPE"
)
