// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// ForgeNamespace provides methods for the forge engine.
//
// Internal certificate authority engine
type ForgeNamespace struct {
	transport Transport
	engine    string
}

func newForgeNamespace(transport Transport, engine string) *ForgeNamespace {
	return &ForgeNamespace{transport: transport, engine: engine}
}

// CaCreate executes CA CREATE — Create a new Certificate Authority
func (ns *ForgeNamespace) CaCreate(ctx context.Context, name string, algorithm string, subject string, opts *ForgeCaCreateOptions) (*ForgeCaCreateResponse, error) {
	args := []string{"CA", "CREATE"}
	args = append(args, fmt.Sprint(name))
	args = append(args, fmt.Sprint(algorithm))
	args = append(args, "SUBJECT")
	args = append(args, fmt.Sprint(subject))
	if opts != nil {
		if opts.TtlDays != nil {
			args = append(args, "TTL_DAYS", fmt.Sprint(*opts.TtlDays))
		}
		if opts.Parent != nil {
			args = append(args, "PARENT", fmt.Sprint(*opts.Parent))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeCaCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CaExport executes CA EXPORT — Export the active CA certificate (PEM)
func (ns *ForgeNamespace) CaExport(ctx context.Context, name string) (*ForgeCaExportResponse, error) {
	args := []string{"CA", "EXPORT"}
	args = append(args, fmt.Sprint(name))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeCaExportResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CaInfo executes CA INFO — Get CA metadata and key version status
func (ns *ForgeNamespace) CaInfo(ctx context.Context, name string) (*ForgeCaInfoResponse, error) {
	args := []string{"CA", "INFO"}
	args = append(args, fmt.Sprint(name))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeCaInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CaList executes CA LIST — List all Certificate Authorities
func (ns *ForgeNamespace) CaList(ctx context.Context) (*ForgeCaListResponse, error) {
	args := []string{"CA", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeCaListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CaRotate executes CA ROTATE — Rotate CA signing key
func (ns *ForgeNamespace) CaRotate(ctx context.Context, name string, opts *ForgeCaRotateOptions) (*ForgeCaRotateResponse, error) {
	args := []string{"CA", "ROTATE"}
	args = append(args, fmt.Sprint(name))
	if opts != nil {
		if opts.Force {
			args = append(args, "FORCE")
		}
		if opts.Dryrun {
			args = append(args, "DRYRUN")
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeCaRotateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ConfigGet executes CONFIG GET — Get a runtime configuration value
func (ns *ForgeNamespace) ConfigGet(ctx context.Context, key string) (*ForgeConfigGetResponse, error) {
	args := []string{"CONFIG", "GET"}
	args = append(args, key)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeConfigGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ConfigSet executes CONFIG SET — Set a runtime configuration value (only scheduler_interval_secs is mutable)
func (ns *ForgeNamespace) ConfigSet(ctx context.Context, key string, value string) (*ForgeConfigSetResponse, error) {
	args := []string{"CONFIG", "SET"}
	args = append(args, key)
	args = append(args, value)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeConfigSetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Inspect executes INSPECT — Get certificate details
func (ns *ForgeNamespace) Inspect(ctx context.Context, ca string, serial string) (*ForgeInspectResponse, error) {
	args := []string{"INSPECT"}
	args = append(args, fmt.Sprint(ca))
	args = append(args, fmt.Sprint(serial))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeInspectResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Issue executes ISSUE — Issue a new certificate. Returns cert + private key (private key never stored).
func (ns *ForgeNamespace) Issue(ctx context.Context, ca string, subject string, profile string, opts *ForgeIssueOptions) (*ForgeIssueResponse, error) {
	args := []string{"ISSUE"}
	args = append(args, fmt.Sprint(ca))
	args = append(args, fmt.Sprint(subject))
	args = append(args, fmt.Sprint(profile))
	if opts != nil {
		if opts.Ttl != nil {
			args = append(args, "TTL", fmt.Sprint(*opts.Ttl))
		}
		if opts.SanDns != nil {
			args = append(args, "SAN_DNS", fmt.Sprint(*opts.SanDns))
		}
		if opts.SanIp != nil {
			args = append(args, "SAN_IP", fmt.Sprint(*opts.SanIp))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeIssueResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// IssueFromCsr executes ISSUE_FROM_CSR — Issue a certificate from a PEM-encoded CSR
func (ns *ForgeNamespace) IssueFromCsr(ctx context.Context, ca string, csr_pem string, profile string, opts *ForgeIssueFromCsrOptions) (*ForgeIssueFromCsrResponse, error) {
	args := []string{"ISSUE_FROM_CSR"}
	args = append(args, fmt.Sprint(ca))
	args = append(args, csr_pem)
	args = append(args, fmt.Sprint(profile))
	if opts != nil {
		if opts.Ttl != nil {
			args = append(args, "TTL", fmt.Sprint(*opts.Ttl))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeIssueFromCsrResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ListCerts executes LIST_CERTS — List certificates for a CA
func (ns *ForgeNamespace) ListCerts(ctx context.Context, ca string, opts *ForgeListCertsOptions) (*ForgeListCertsResponse, error) {
	args := []string{"LIST_CERTS"}
	args = append(args, fmt.Sprint(ca))
	if opts != nil {
		if opts.State != nil {
			args = append(args, "STATE", fmt.Sprint(*opts.State))
		}
		if opts.Limit != nil {
			args = append(args, "LIMIT", fmt.Sprint(*opts.Limit))
		}
		if opts.Offset != nil {
			args = append(args, "OFFSET", fmt.Sprint(*opts.Offset))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeListCertsResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Renew executes RENEW — Renew a certificate (re-issue with same profile and SANs)
func (ns *ForgeNamespace) Renew(ctx context.Context, ca string, serial string, opts *ForgeRenewOptions) (*ForgeRenewResponse, error) {
	args := []string{"RENEW"}
	args = append(args, fmt.Sprint(ca))
	args = append(args, fmt.Sprint(serial))
	if opts != nil {
		if opts.Ttl != nil {
			args = append(args, "TTL", fmt.Sprint(*opts.Ttl))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeRenewResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Revoke executes REVOKE — Revoke a certificate
func (ns *ForgeNamespace) Revoke(ctx context.Context, ca string, serial string, opts *ForgeRevokeOptions) (*ForgeRevokeResponse, error) {
	args := []string{"REVOKE"}
	args = append(args, fmt.Sprint(ca))
	args = append(args, fmt.Sprint(serial))
	if opts != nil {
		if opts.Reason != nil {
			args = append(args, "REASON", fmt.Sprint(*opts.Reason))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ForgeRevokeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
