// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// HttpTransport implements Transport via HTTP POST to a Moat gateway.
// Commands are sent as JSON to /v1/{engine}.
type HttpTransport struct {
	baseURL  string
	token    string
	client   *http.Client
	prefixes map[string]string
}

// NewHttpTransport creates an HTTP transport for the given Moat base URL.
func NewHttpTransport(baseURL string, token string, prefixes map[string]string) *HttpTransport {
	return &HttpTransport{
		baseURL:  strings.TrimRight(baseURL, "/"),
		token:    token,
		client:   &http.Client{},
		prefixes: prefixes,
	}
}

// Execute sends a command as an HTTP POST and returns the parsed response.
func (t *HttpTransport) Execute(ctx context.Context, engine string, args []string) (map[string]any, error) {
	prefix, ok := t.prefixes[engine]
	if !ok {
		prefix = fmt.Sprintf("/v1/%s", engine)
	}
	endpoint := t.baseURL + prefix

	body, err := json.Marshal(map[string]any{"args": args})
	if err != nil {
		return nil, fmt.Errorf("http: marshal: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("http: request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if t.token != "" {
		req.Header.Set("Authorization", "Bearer "+t.token)
	}

	resp, err := t.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("http: do: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("http: read body: %w", err)
	}

	if resp.StatusCode >= 400 {
		code := "INTERNAL"
		detail := string(respBody)
		var errResp map[string]any
		if json.Unmarshal(respBody, &errResp) == nil {
			if errMsg, ok := errResp["error"].(string); ok {
				parts := strings.SplitN(errMsg, " ", 2)
				code = parts[0]
				if len(parts) > 1 {
					detail = parts[1]
				} else {
					detail = errMsg
				}
			}
		}
		return nil, &ShrouDBError{Code: code, Message: detail}
	}

	var result map[string]any
	if err := json.Unmarshal(respBody, &result); err != nil {
		return nil, fmt.Errorf("http: unmarshal response: %w", err)
	}
	return result, nil
}

// Close is a no-op for HTTP transport (stateless).
func (t *HttpTransport) Close() error {
	return nil
}
