// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
)

// KeepNamespace provides methods for the keep engine.
//
// Secrets manager with path-based access control and versioning
type KeepNamespace struct {
	transport Transport
	engine    string
}

func newKeepNamespace(transport Transport, engine string) *KeepNamespace {
	return &KeepNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate this connection with a token.
func (ns *KeepNamespace) Auth(ctx context.Context, token string) (*KeepAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List all supported commands.
func (ns *KeepNamespace) CommandList(ctx context.Context) (*KeepCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Delete executes DELETE — Soft-delete a secret. Version history is preserved.
func (ns *KeepNamespace) Delete(ctx context.Context, path string) (*KeepDeleteResponse, error) {
	args := []string{"DELETE"}
	args = append(args, fmt.Sprint(path))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Get executes GET — Retrieve a secret value. Returns the latest version by default.
func (ns *KeepNamespace) Get(ctx context.Context, path string, opts *KeepGetOptions) (*KeepGetResponse, error) {
	args := []string{"GET"}
	args = append(args, fmt.Sprint(path))
	if opts != nil {
		if opts.Version != nil {
			args = append(args, "VERSION", fmt.Sprint(*opts.Version))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// KeepGetCall carries one call for the GetMany batch helper.
type KeepGetCall struct {
	Path string
	Version *int
}

// GetMany — batch variant: pipelines N independent calls over one connection (ordered, not atomic).
func (ns *KeepNamespace) GetMany(ctx context.Context, calls []KeepGetCall) ([]map[string]any, error) {
	argsList := make([][]string, 0, len(calls))
	for _, call := range calls {
		args := []string{"GET"}
		args = append(args, fmt.Sprint(call.Path))
		if call.Version != nil {
			args = append(args, "VERSION", fmt.Sprint(*call.Version))
		}
		argsList = append(argsList, args)
	}
	return ns.transport.ExecuteMany(ctx, ns.engine, argsList)
}

// Health executes HEALTH — Health check.
func (ns *KeepNamespace) Health(ctx context.Context) (*KeepHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Hello executes HELLO — Engine identity handshake — returns engine name, version, wire protocol, supported commands, and capability tags. Pre-auth; clients issue this on connect to verify they are talking to the expected engine and version.
func (ns *KeepNamespace) Hello(ctx context.Context) (*KeepHelloResponse, error) {
	args := []string{"HELLO"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepHelloResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// List executes LIST — List secret paths, optionally filtered by prefix. Excludes deleted secrets.
func (ns *KeepNamespace) List(ctx context.Context, prefix string) (*KeepListResponse, error) {
	args := []string{"LIST"}
	if prefix != "" {
		args = append(args, prefix)
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Ping-pong.
func (ns *KeepNamespace) Ping(ctx context.Context) error {
	args := []string{"PING"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Purge executes PURGE — Permanently remove a secret and all its versions. Irreversible — used for GDPR right-to-erasure compliance. After purge, GET returns not-found (not deleted).
func (ns *KeepNamespace) Purge(ctx context.Context, path string) (*KeepPurgeResponse, error) {
	args := []string{"PURGE"}
	args = append(args, fmt.Sprint(path))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepPurgeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Put executes PUT — Store a new version of a secret. Creates the secret if it doesn't exist. Undeletes if soft-deleted.
func (ns *KeepNamespace) Put(ctx context.Context, path string, value []byte) (*KeepPutResponse, error) {
	args := []string{"PUT"}
	args = append(args, fmt.Sprint(path))
	args = append(args, base64.StdEncoding.EncodeToString(value))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepPutResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Rekey executes REKEY — Re-encrypt all secrets with a new master key. Iterates all secrets (including deleted ones), decrypts every version with the current master key, re-encrypts with the new key, and switches to the new key for all future operations.
func (ns *KeepNamespace) Rekey(ctx context.Context, new_key string) (*KeepRekeyResponse, error) {
	args := []string{"REKEY"}
	args = append(args, new_key)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepRekeyResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Rotate executes ROTATE — Re-encrypt the latest version with a new nonce. Creates a new version with the same plaintext.
func (ns *KeepNamespace) Rotate(ctx context.Context, path string) (*KeepRotateResponse, error) {
	args := []string{"ROTATE"}
	args = append(args, fmt.Sprint(path))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepRotateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Versions executes VERSIONS — Get version history for a secret. Includes deleted secrets.
func (ns *KeepNamespace) Versions(ctx context.Context, path string) (*KeepVersionsResponse, error) {
	args := []string{"VERSIONS"}
	args = append(args, fmt.Sprint(path))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp KeepVersionsResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
