// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// ScrollNamespace provides methods for the scroll engine.
//
// Durable append-only event log with cursored readers and reader groups
type ScrollNamespace struct {
	transport Transport
	engine    string
}

func newScrollNamespace(transport Transport, engine string) *ScrollNamespace {
	return &ScrollNamespace{transport: transport, engine: engine}
}

// Ack executes ACK — Acknowledge a pending entry. Idempotent.
func (ns *ScrollNamespace) Ack(ctx context.Context, log string, group string, offset int) (*ScrollAckResponse, error) {
	args := []string{"ACK"}
	args = append(args, log)
	args = append(args, group)
	args = append(args, fmt.Sprint(offset))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollAckResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Append executes APPEND — Append an entry to a log. Mints a monotonic offset through the per-log serializer and encrypts the entry with the per-log DEK.
func (ns *ScrollNamespace) Append(ctx context.Context, log string, payload_b64 any, opts *ScrollAppendOptions) (*ScrollAppendResponse, error) {
	args := []string{"APPEND"}
	args = append(args, log)
	args = append(args, fmt.Sprint(payload_b64))
	if opts != nil {
		if opts.Headers != nil {
			jsonBytes, err := json.Marshal(opts.Headers)
			if err == nil {
				args = append(args, "HEADERS", string(jsonBytes))
			}
		}
		if opts.TtlMs != nil {
			args = append(args, "TTL_MS", fmt.Sprint(*opts.TtlMs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollAppendResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Auth executes AUTH — Authenticate the connection. Consumed at the connection layer before dispatch.
func (ns *ScrollNamespace) Auth(ctx context.Context, token string) (*ScrollAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Claim executes CLAIM — Reassign stalled pending entries to a new reader. Entries whose delivery_count would cross max_delivery_count are moved to scroll.dlq instead.
func (ns *ScrollNamespace) Claim(ctx context.Context, log string, group string, reader_id string, min_idle_ms int) (*ScrollClaimResponse, error) {
	args := []string{"CLAIM"}
	args = append(args, log)
	args = append(args, group)
	args = append(args, reader_id)
	args = append(args, fmt.Sprint(min_idle_ms))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollClaimResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List all supported commands with their syntax.
func (ns *ScrollNamespace) CommandList(ctx context.Context) (*ScrollCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CreateGroup executes CREATE_GROUP — Create a reader group. start_offset = 'earliest' | '0' starts from offset 0; 'latest' | '-1' starts after the current tail.
func (ns *ScrollNamespace) CreateGroup(ctx context.Context, log string, group string, start_offset string) (*ScrollCreateGroupResponse, error) {
	args := []string{"CREATE_GROUP"}
	args = append(args, log)
	args = append(args, group)
	args = append(args, start_offset)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollCreateGroupResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// DeleteGroup executes DELETE_GROUP — Tear down a single reader group: delete every pending record, then remove the group row. Counterpart to CREATE_GROUP; doesn't touch scroll.logs or the DEK, so other groups on the same log keep operating. Returns 'group not found' when the target doesn't exist.
func (ns *ScrollNamespace) DeleteGroup(ctx context.Context, log string, group string) (*ScrollDeleteGroupResponse, error) {
	args := []string{"DELETE_GROUP"}
	args = append(args, log)
	args = append(args, group)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollDeleteGroupResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// DeleteLog executes DELETE_LOG — Hard-delete all log state (entries, groups, pending, offset counter) and destroy the wrapped DEK to crypto-shred.
func (ns *ScrollNamespace) DeleteLog(ctx context.Context, log string) (*ScrollDeleteLogResponse, error) {
	args := []string{"DELETE_LOG"}
	args = append(args, log)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollDeleteLogResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// GroupInfo executes GROUP_INFO — Stats for a reader group: cursor, members, and pending entry count.
func (ns *ScrollNamespace) GroupInfo(ctx context.Context, log string, group string) (*ScrollGroupInfoResponse, error) {
	args := []string{"GROUP_INFO"}
	args = append(args, log)
	args = append(args, group)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollGroupInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Engine liveness probe.
func (ns *ScrollNamespace) Health(ctx context.Context) (*ScrollHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Hello executes HELLO — Engine identity + version + supported commands. Pre-auth version-detection handshake.
func (ns *ScrollNamespace) Hello(ctx context.Context) (*ScrollHelloResponse, error) {
	args := []string{"HELLO"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollHelloResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// LogInfo executes LOG_INFO — Stats for a log: entries minted, latest offset, created-at, and list of reader groups.
func (ns *ScrollNamespace) LogInfo(ctx context.Context, log string) (*ScrollLogInfoResponse, error) {
	args := []string{"LOG_INFO"}
	args = append(args, log)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollLogInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Connection liveness probe. Returns PONG.
func (ns *ScrollNamespace) Ping(ctx context.Context) error {
	args := []string{"PING"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Read executes READ — Range read starting at from_offset. Missing offsets (trimmed / TTL-expired) are skipped silently.
func (ns *ScrollNamespace) Read(ctx context.Context, log string, from_offset int, limit int) (*ScrollReadResponse, error) {
	args := []string{"READ"}
	args = append(args, log)
	args = append(args, fmt.Sprint(from_offset))
	args = append(args, fmt.Sprint(limit))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollReadResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ReadGroup executes READ_GROUP — Advance the group cursor under CAS on `scroll.groups`, register PendingEntry records, and return the decrypted batch.
func (ns *ScrollNamespace) ReadGroup(ctx context.Context, log string, group string, reader_id string, limit int) (*ScrollReadGroupResponse, error) {
	args := []string{"READ_GROUP"}
	args = append(args, log)
	args = append(args, group)
	args = append(args, reader_id)
	args = append(args, fmt.Sprint(limit))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollReadGroupResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Replay executes REPLAY — Move a DLQ entry back into a group's pending set. Preserves the original reader_id from the DLQ record, resets delivery_count to 1, stamps a fresh delivered_at_ms. Put-pending-first / delete-dlq-second ordering: a crash in-between leaves a duplicate, never a loss. Returns 'dlq entry not found' when the offset has no DLQ record, 'group not found' when the target group doesn't exist.
func (ns *ScrollNamespace) Replay(ctx context.Context, log string, group string, offset int) (*ScrollReplayResponse, error) {
	args := []string{"REPLAY"}
	args = append(args, log)
	args = append(args, group)
	args = append(args, fmt.Sprint(offset))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollReplayResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Tail executes TAIL — Live tail: returns at most limit entries at or after from_offset, waiting up to TIMEOUT ms (default 30_000) for new appends. Closes with TAIL_OVERFLOW on subscribe backpressure; client should fall back to READ.
func (ns *ScrollNamespace) Tail(ctx context.Context, log string, from_offset int, limit int, opts *ScrollTailOptions) (*ScrollTailResponse, error) {
	args := []string{"TAIL"}
	args = append(args, log)
	args = append(args, fmt.Sprint(from_offset))
	args = append(args, fmt.Sprint(limit))
	if opts != nil {
		if opts.TimeoutMs != nil {
			args = append(args, "TIMEOUT_MS", fmt.Sprint(*opts.TimeoutMs))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollTailResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Trim executes TRIM — Explicit retention. MAX_LEN keeps the most recent N offsets; MAX_AGE drops entries whose appended_at_ms is older than now-ms.
func (ns *ScrollNamespace) Trim(ctx context.Context, log string, selector string, value int) (*ScrollTrimResponse, error) {
	args := []string{"TRIM"}
	args = append(args, log)
	args = append(args, "MAX_LEN")
	args = append(args, selector)
	args = append(args, "TRIM")
	args = append(args, fmt.Sprint(value))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ScrollTrimResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
