// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// SentryNamespace provides methods for the sentry engine.
//
// sentry
type SentryNamespace struct {
	transport Transport
	engine    string
}

func newSentryNamespace(transport Transport, engine string) *SentryNamespace {
	return &SentryNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate the connection with a token
func (ns *SentryNamespace) Auth(ctx context.Context, token string) (*SentryAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List all supported commands
func (ns *SentryNamespace) CommandList(ctx context.Context) (*SentryCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Evaluate executes EVALUATE — Evaluate an authorization request against policies and return a signed decision
func (ns *SentryNamespace) Evaluate(ctx context.Context, jsonData string) (*SentryEvaluateResponse, error) {
	args := []string{"EVALUATE"}
	args = append(args, fmt.Sprint(jsonData))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryEvaluateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Server health check
func (ns *SentryNamespace) Health(ctx context.Context) (*SentryHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Jwks executes JWKS — Get the JSON Web Key Set for verifying decision tokens
func (ns *SentryNamespace) Jwks(ctx context.Context) (*SentryJwksResponse, error) {
	args := []string{"JWKS"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryJwksResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// KeyInfo executes KEY INFO — Get signing key metadata
func (ns *SentryNamespace) KeyInfo(ctx context.Context) (*SentryKeyInfoResponse, error) {
	args := []string{"KEY", "INFO"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryKeyInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// KeyRotate executes KEY ROTATE — Rotate the signing key
func (ns *SentryNamespace) KeyRotate(ctx context.Context, opts *SentryKeyRotateOptions) (*SentryKeyRotateResponse, error) {
	args := []string{"KEY", "ROTATE"}
	if opts != nil {
		if opts.Force != nil {
			args = append(args, "FORCE", fmt.Sprint(*opts.Force))
		}
		if opts.Dryrun != nil {
			args = append(args, "DRYRUN", fmt.Sprint(*opts.Dryrun))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryKeyRotateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Connectivity check
func (ns *SentryNamespace) Ping(ctx context.Context) error {
	args := []string{"PING"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// PolicyCreate executes POLICY CREATE — Create a new authorization policy
func (ns *SentryNamespace) PolicyCreate(ctx context.Context, name string, jsonData string) (*SentryPolicyCreateResponse, error) {
	args := []string{"POLICY", "CREATE"}
	args = append(args, fmt.Sprint(name))
	args = append(args, fmt.Sprint(jsonData))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryPolicyCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// PolicyDelete executes POLICY DELETE — Delete a policy
func (ns *SentryNamespace) PolicyDelete(ctx context.Context, name string) (*SentryPolicyDeleteResponse, error) {
	args := []string{"POLICY", "DELETE"}
	args = append(args, fmt.Sprint(name))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryPolicyDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// PolicyGet executes POLICY GET — Get a policy by name
func (ns *SentryNamespace) PolicyGet(ctx context.Context, name string) (*SentryPolicyGetResponse, error) {
	args := []string{"POLICY", "GET"}
	args = append(args, fmt.Sprint(name))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryPolicyGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// PolicyList executes POLICY LIST — List all policy names
func (ns *SentryNamespace) PolicyList(ctx context.Context) (*SentryPolicyListResponse, error) {
	args := []string{"POLICY", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryPolicyListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// PolicyUpdate executes POLICY UPDATE — Update an existing policy
func (ns *SentryNamespace) PolicyUpdate(ctx context.Context, name string, jsonData string) (*SentryPolicyUpdateResponse, error) {
	args := []string{"POLICY", "UPDATE"}
	args = append(args, fmt.Sprint(name))
	args = append(args, fmt.Sprint(jsonData))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SentryPolicyUpdateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
