// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// ShroudbNamespace provides methods for the shroudb engine.
//
// Encrypted key-value database
type ShroudbNamespace struct {
	transport Transport
	engine    string
}

func newShroudbNamespace(transport Transport, engine string) *ShroudbNamespace {
	return &ShroudbNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate the connection with a token
func (ns *ShroudbNamespace) Auth(ctx context.Context, token string) (*ShroudbAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List all supported commands
func (ns *ShroudbNamespace) CommandList(ctx context.Context) (*ShroudbCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ConfigGet executes CONFIG GET — Read a runtime configuration value
func (ns *ShroudbNamespace) ConfigGet(ctx context.Context, key string) (*ShroudbConfigGetResponse, error) {
	args := []string{"CONFIG", "GET"}
	args = append(args, key)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbConfigGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// ConfigSet executes CONFIG SET — Set a runtime configuration value (admin only). Only registered config keys are accepted; unknown keys return an error. Values are type-checked against the key's schema (u64, bool, string). Valid keys: max_segment_bytes, max_segment_entries, snapshot_entry_threshold, snapshot_time_threshold_secs.
func (ns *ShroudbNamespace) ConfigSet(ctx context.Context, key string, value string) error {
	args := []string{"CONFIG", "SET"}
	args = append(args, key)
	args = append(args, value)
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Delete executes DELETE — Delete a key by writing a tombstone
func (ns *ShroudbNamespace) Delete(ctx context.Context, namespace string, key string) (*ShroudbDeleteResponse, error) {
	args := []string{"DELETE"}
	args = append(args, namespace)
	args = append(args, key)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Get executes GET — Retrieve the value at a key
func (ns *ShroudbNamespace) Get(ctx context.Context, namespace string, key string, META bool, opts *ShroudbGetOptions) (*ShroudbGetResponse, error) {
	args := []string{"GET"}
	args = append(args, namespace)
	args = append(args, key)
	if META {
		args = append(args, fmt.Sprint(META))
	}
	if opts != nil {
		if opts.Version != nil {
			args = append(args, "VERSION", fmt.Sprint(*opts.Version))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Check server health
func (ns *ShroudbNamespace) Health(ctx context.Context) (*ShroudbHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// List executes LIST — List active keys in a namespace. Returns an error if the CURSOR value does not correspond to a key that exists in the namespace.
func (ns *ShroudbNamespace) List(ctx context.Context, namespace string, opts *ShroudbListOptions) (*ShroudbListResponse, error) {
	args := []string{"LIST"}
	args = append(args, namespace)
	if opts != nil {
		if opts.Prefix != nil {
			args = append(args, "PREFIX", fmt.Sprint(*opts.Prefix))
		}
		if opts.Cursor != nil {
			args = append(args, "CURSOR", fmt.Sprint(*opts.Cursor))
		}
		if opts.Limit != nil {
			args = append(args, "LIMIT", fmt.Sprint(*opts.Limit))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// NamespaceAlter executes NAMESPACE ALTER — Update namespace configuration (enforce-on-write-only)
func (ns *ShroudbNamespace) NamespaceAlter(ctx context.Context, name string, opts *ShroudbNamespaceAlterOptions) error {
	args := []string{"NAMESPACE", "ALTER"}
	args = append(args, name)
	if opts != nil {
		if opts.Schema != nil {
			jsonBytes, err := json.Marshal(opts.Schema)
			if err == nil {
				args = append(args, "SCHEMA", string(jsonBytes))
			}
		}
		if opts.MaxVersions != nil {
			args = append(args, "MAX_VERSIONS", fmt.Sprint(*opts.MaxVersions))
		}
		if opts.TombstoneRetention != nil {
			args = append(args, "TOMBSTONE_RETENTION", fmt.Sprint(*opts.TombstoneRetention))
		}
	}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// NamespaceCreate executes NAMESPACE CREATE — Create a new namespace
func (ns *ShroudbNamespace) NamespaceCreate(ctx context.Context, name string, opts *ShroudbNamespaceCreateOptions) error {
	args := []string{"NAMESPACE", "CREATE"}
	args = append(args, name)
	if opts != nil {
		if opts.Schema != nil {
			jsonBytes, err := json.Marshal(opts.Schema)
			if err == nil {
				args = append(args, "SCHEMA", string(jsonBytes))
			}
		}
		if opts.MaxVersions != nil {
			args = append(args, "MAX_VERSIONS", fmt.Sprint(*opts.MaxVersions))
		}
		if opts.TombstoneRetention != nil {
			args = append(args, "TOMBSTONE_RETENTION", fmt.Sprint(*opts.TombstoneRetention))
		}
	}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// NamespaceDrop executes NAMESPACE DROP — Drop a namespace
func (ns *ShroudbNamespace) NamespaceDrop(ctx context.Context, name string, FORCE bool) error {
	args := []string{"NAMESPACE", "DROP"}
	args = append(args, name)
	if FORCE {
		args = append(args, fmt.Sprint(FORCE))
	}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// NamespaceInfo executes NAMESPACE INFO — Get metadata about a namespace
func (ns *ShroudbNamespace) NamespaceInfo(ctx context.Context, name string) (*ShroudbNamespaceInfoResponse, error) {
	args := []string{"NAMESPACE", "INFO"}
	args = append(args, name)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbNamespaceInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// NamespaceList executes NAMESPACE LIST — List namespaces (filtered by token grants)
func (ns *ShroudbNamespace) NamespaceList(ctx context.Context, opts *ShroudbNamespaceListOptions) (*ShroudbNamespaceListResponse, error) {
	args := []string{"NAMESPACE", "LIST"}
	if opts != nil {
		if opts.Cursor != nil {
			args = append(args, "CURSOR", fmt.Sprint(*opts.Cursor))
		}
		if opts.Limit != nil {
			args = append(args, "LIMIT", fmt.Sprint(*opts.Limit))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbNamespaceListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// NamespaceValidate executes NAMESPACE VALIDATE — Check existing entries against current MetaSchema
func (ns *ShroudbNamespace) NamespaceValidate(ctx context.Context, name string) (*ShroudbNamespaceValidateResponse, error) {
	args := []string{"NAMESPACE", "VALIDATE"}
	args = append(args, name)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbNamespaceValidateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Test connectivity
func (ns *ShroudbNamespace) Ping(ctx context.Context) (*ShroudbPingResponse, error) {
	args := []string{"PING"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbPingResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Pipeline — Execute commands atomically (all succeed or all roll back)
func (ns *ShroudbNamespace) Pipeline(ctx context.Context, commands [][]string, requestID string) ([]map[string]any, error) {
	return ns.transport.ExecutePipeline(ctx, ns.engine, commands, requestID)
}

// Put executes PUT — Store a value at the given key. Auto-increments version.
func (ns *ShroudbNamespace) Put(ctx context.Context, namespace string, key string, value string, opts *ShroudbPutOptions) (*ShroudbPutResponse, error) {
	args := []string{"PUT"}
	args = append(args, namespace)
	args = append(args, key)
	if value != "" {
		args = append(args, value)
	}
	if opts != nil {
		if opts.Meta != nil {
			jsonBytes, err := json.Marshal(opts.Meta)
			if err == nil {
				args = append(args, "META", string(jsonBytes))
			}
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbPutResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Rekey executes REKEY — Begin online rekey (zero-downtime master key rotation)
func (ns *ShroudbNamespace) Rekey(ctx context.Context) (*ShroudbRekeyResponse, error) {
	args := []string{"REKEY"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbRekeyResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// RekeyStatus executes REKEY STATUS — Query progress of an in-flight rekey operation
func (ns *ShroudbNamespace) RekeyStatus(ctx context.Context) (*ShroudbRekeyStatusResponse, error) {
	args := []string{"REKEY", "STATUS"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbRekeyStatusResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Subscribe executes SUBSCRIBE — Subscribe to change events on a namespace
func (ns *ShroudbNamespace) Subscribe(ctx context.Context, namespace string, opts *ShroudbSubscribeOptions) error {
	args := []string{"SUBSCRIBE"}
	args = append(args, namespace)
	if opts != nil {
		if opts.Key != nil {
			args = append(args, "KEY", fmt.Sprint(*opts.Key))
		}
		if opts.Events != nil {
			args = append(args, "EVENTS", fmt.Sprint(*opts.Events))
		}
	}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Unsubscribe executes UNSUBSCRIBE — End the current subscription
func (ns *ShroudbNamespace) Unsubscribe(ctx context.Context) error {
	args := []string{"UNSUBSCRIBE"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Versions executes VERSIONS — Retrieve version history for a key (most recent first)
func (ns *ShroudbNamespace) Versions(ctx context.Context, namespace string, key string, opts *ShroudbVersionsOptions) (*ShroudbVersionsResponse, error) {
	args := []string{"VERSIONS"}
	args = append(args, namespace)
	args = append(args, key)
	if opts != nil {
		if opts.Limit != nil {
			args = append(args, "LIMIT", fmt.Sprint(*opts.Limit))
		}
		if opts.From != nil {
			args = append(args, "FROM", fmt.Sprint(*opts.From))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp ShroudbVersionsResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
