// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// SigilNamespace provides methods for the sigil engine.
//
// Schema-driven credential envelope engine
type SigilNamespace struct {
	transport Transport
	engine    string
}

func newSigilNamespace(transport Transport, engine string) *SigilNamespace {
	return &SigilNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate the current TCP connection with a bearer token. Handled at the connection layer, not dispatched to the engine. HTTP transport uses the Authorization: Bearer header instead.
func (ns *SigilNamespace) Auth(ctx context.Context, token string) (*SigilAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CredentialChange executes CREDENTIAL CHANGE — Change a credential field (requires old value for verification)
func (ns *SigilNamespace) CredentialChange(ctx context.Context, schema string, id string, field string, oldValue string, newValue string) (*SigilCredentialChangeResponse, error) {
	args := []string{"CREDENTIAL", "CHANGE"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, field)
	args = append(args, oldValue)
	args = append(args, newValue)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilCredentialChangeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CredentialImport executes CREDENTIAL IMPORT — Import a pre-hashed credential (bcrypt, scrypt, argon2). Transparently rehashed to Argon2id on next verify.
func (ns *SigilNamespace) CredentialImport(ctx context.Context, schema string, id string, field string, hash string, opts *SigilCredentialImportOptions) (*SigilCredentialImportResponse, error) {
	args := []string{"CREDENTIAL", "IMPORT"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, field)
	args = append(args, hash)
	if opts != nil {
		if opts.Meta != nil {
			jsonBytes, err := json.Marshal(opts.Meta)
			if err == nil {
				args = append(args, "META", string(jsonBytes))
			}
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilCredentialImportResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CredentialReset executes CREDENTIAL RESET — Force-reset a credential field without requiring old value (admin/reset token)
func (ns *SigilNamespace) CredentialReset(ctx context.Context, schema string, id string, field string, newValue string) (*SigilCredentialResetResponse, error) {
	args := []string{"CREDENTIAL", "RESET"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, field)
	args = append(args, newValue)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilCredentialResetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeCreate executes ENVELOPE CREATE — Create an envelope with field routing per schema kind
func (ns *SigilNamespace) EnvelopeCreate(ctx context.Context, schema string, id string, jsonData any) (*SigilEnvelopeCreateResponse, error) {
	args := []string{"ENVELOPE", "CREATE"}
	args = append(args, schema)
	args = append(args, id)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeDelete executes ENVELOPE DELETE — Delete an envelope and all associated data
func (ns *SigilNamespace) EnvelopeDelete(ctx context.Context, schema string, id string) (*SigilEnvelopeDeleteResponse, error) {
	args := []string{"ENVELOPE", "DELETE"}
	args = append(args, schema)
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeGet executes ENVELOPE GET — Get an envelope record
func (ns *SigilNamespace) EnvelopeGet(ctx context.Context, schema string, id string) (*SigilEnvelopeGetResponse, error) {
	args := []string{"ENVELOPE", "GET"}
	args = append(args, schema)
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeImport executes ENVELOPE IMPORT — Import an envelope with pre-hashed credential fields. Non-credential fields processed normally.
func (ns *SigilNamespace) EnvelopeImport(ctx context.Context, schema string, id string, jsonData any) (*SigilEnvelopeImportResponse, error) {
	args := []string{"ENVELOPE", "IMPORT"}
	args = append(args, schema)
	args = append(args, id)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeImportResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeLookup executes ENVELOPE LOOKUP — Look up an envelope by indexed or searchable field value. Returns the matched entity ID only.
func (ns *SigilNamespace) EnvelopeLookup(ctx context.Context, schema string, field string, value string) (*SigilEnvelopeLookupResponse, error) {
	args := []string{"ENVELOPE", "LOOKUP"}
	args = append(args, schema)
	args = append(args, field)
	args = append(args, value)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeLookupResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeUpdate executes ENVELOPE UPDATE — Update non-credential fields on an existing envelope
func (ns *SigilNamespace) EnvelopeUpdate(ctx context.Context, schema string, id string, jsonData any) (*SigilEnvelopeUpdateResponse, error) {
	args := []string{"ENVELOPE", "UPDATE"}
	args = append(args, schema)
	args = append(args, id)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeUpdateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// EnvelopeVerify executes ENVELOPE VERIFY — Verify a credential field on an envelope by explicit field name
func (ns *SigilNamespace) EnvelopeVerify(ctx context.Context, schema string, id string, field string, value string) (*SigilEnvelopeVerifyResponse, error) {
	args := []string{"ENVELOPE", "VERIFY"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, field)
	args = append(args, value)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilEnvelopeVerifyResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Health check
func (ns *SigilNamespace) Health(ctx context.Context) (*SigilHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Jwks executes JWKS — Get the JSON Web Key Set for external token verification
func (ns *SigilNamespace) Jwks(ctx context.Context, schema string) error {
	args := []string{"JWKS"}
	args = append(args, schema)
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// PasswordChange executes PASSWORD CHANGE — Sugar: change password. Infers credential field from schema. Equivalent to CREDENTIAL CHANGE with implicit field.
func (ns *SigilNamespace) PasswordChange(ctx context.Context, schema string, id string, oldValue string, newValue string) (*SigilPasswordChangeResponse, error) {
	args := []string{"PASSWORD", "CHANGE"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, oldValue)
	args = append(args, newValue)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilPasswordChangeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// PasswordImport executes PASSWORD IMPORT — Sugar: import pre-hashed password. Infers credential field from schema. Equivalent to CREDENTIAL IMPORT with implicit field.
func (ns *SigilNamespace) PasswordImport(ctx context.Context, schema string, id string, hash string, opts *SigilPasswordImportOptions) (*SigilPasswordImportResponse, error) {
	args := []string{"PASSWORD", "IMPORT"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, hash)
	if opts != nil {
		if opts.Meta != nil {
			jsonBytes, err := json.Marshal(opts.Meta)
			if err == nil {
				args = append(args, "META", string(jsonBytes))
			}
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilPasswordImportResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// PasswordReset executes PASSWORD RESET — Sugar: force-reset password. Infers credential field from schema. Equivalent to CREDENTIAL RESET with implicit field.
func (ns *SigilNamespace) PasswordReset(ctx context.Context, schema string, id string, newValue string) (*SigilPasswordResetResponse, error) {
	args := []string{"PASSWORD", "RESET"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, newValue)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilPasswordResetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Ping-pong connectivity test
func (ns *SigilNamespace) Ping(ctx context.Context) (*SigilPingResponse, error) {
	args := []string{"PING"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilPingResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SchemaAlter executes SCHEMA ALTER — Add or remove fields from a schema, producing a new version. Added fields are optional (required=false). Existing envelopes remain readable.
func (ns *SigilNamespace) SchemaAlter(ctx context.Context, name string, action string, opts *SigilSchemaAlterOptions) (*SigilSchemaAlterResponse, error) {
	args := []string{"SCHEMA", "ALTER"}
	args = append(args, name)
	args = append(args, "ADD")
	args = append(args, action)
	if opts != nil {
		if opts.FieldJson != nil {
			jsonBytes, err := json.Marshal(opts.FieldJson)
			if err == nil {
				args = append(args, "FIELD_JSON", string(jsonBytes))
			}
		}
		if opts.FieldName != nil {
			args = append(args, "FIELD_NAME", fmt.Sprint(*opts.FieldName))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSchemaAlterResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SchemaGet executes SCHEMA GET — Get a schema definition by name
func (ns *SigilNamespace) SchemaGet(ctx context.Context, name string) error {
	args := []string{"SCHEMA", "GET"}
	args = append(args, name)
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// SchemaList executes SCHEMA LIST — List all registered schema names
func (ns *SigilNamespace) SchemaList(ctx context.Context) error {
	args := []string{"SCHEMA", "LIST"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// SchemaRegister executes SCHEMA REGISTER — Register a credential envelope schema
func (ns *SigilNamespace) SchemaRegister(ctx context.Context, name string, jsonData any) (*SigilSchemaRegisterResponse, error) {
	args := []string{"SCHEMA", "REGISTER"}
	args = append(args, name)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSchemaRegisterResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SessionCreate executes SESSION CREATE — Verify credentials and issue access + refresh tokens. Fields annotated with claim=true are auto-included in the JWT from the entity's envelope. Enriched claim values override caller-provided META for the same key.
func (ns *SigilNamespace) SessionCreate(ctx context.Context, schema string, id string, password string, opts *SigilSessionCreateOptions) (*SigilSessionCreateResponse, error) {
	args := []string{"SESSION", "CREATE"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, password)
	if opts != nil {
		if opts.Meta != nil {
			jsonBytes, err := json.Marshal(opts.Meta)
			if err == nil {
				args = append(args, "META", string(jsonBytes))
			}
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSessionCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SessionList executes SESSION LIST — List active sessions for an entity
func (ns *SigilNamespace) SessionList(ctx context.Context, schema string, id string) error {
	args := []string{"SESSION", "LIST"}
	args = append(args, schema)
	args = append(args, id)
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// SessionLogin executes SESSION LOGIN — Verify credentials by indexed field value (e.g., email) and issue access + refresh tokens. Same claim enrichment as SESSION CREATE.
func (ns *SigilNamespace) SessionLogin(ctx context.Context, schema string, field string, value string, password string, opts *SigilSessionLoginOptions) (*SigilSessionLoginResponse, error) {
	args := []string{"SESSION", "LOGIN"}
	args = append(args, schema)
	args = append(args, field)
	args = append(args, value)
	args = append(args, password)
	if opts != nil {
		if opts.Meta != nil {
			jsonBytes, err := json.Marshal(opts.Meta)
			if err == nil {
				args = append(args, "META", string(jsonBytes))
			}
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSessionLoginResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SessionRefresh executes SESSION REFRESH — Rotate refresh token and issue new access token. Fields annotated with claim=true are re-read from the entity's current envelope, so refreshed tokens reflect the latest values (e.g. role changes).
func (ns *SigilNamespace) SessionRefresh(ctx context.Context, schema string, token string) (*SigilSessionRefreshResponse, error) {
	args := []string{"SESSION", "REFRESH"}
	args = append(args, schema)
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSessionRefreshResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SessionRevoke executes SESSION REVOKE — Revoke a single refresh token (logout one session)
func (ns *SigilNamespace) SessionRevoke(ctx context.Context, schema string, token string) (*SigilSessionRevokeResponse, error) {
	args := []string{"SESSION", "REVOKE"}
	args = append(args, schema)
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSessionRevokeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// SessionRevokeAll executes SESSION REVOKE ALL — Revoke all sessions for an entity (logout everywhere)
func (ns *SigilNamespace) SessionRevokeAll(ctx context.Context, schema string, id string) (*SigilSessionRevokeAllResponse, error) {
	args := []string{"SESSION", "REVOKE ALL"}
	args = append(args, schema)
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilSessionRevokeAllResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserCreate executes USER CREATE — Sugar: create an envelope. Equivalent to ENVELOPE CREATE.
func (ns *SigilNamespace) UserCreate(ctx context.Context, schema string, id string, jsonData any) (*SigilUserCreateResponse, error) {
	args := []string{"USER", "CREATE"}
	args = append(args, schema)
	args = append(args, id)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserDelete executes USER DELETE — Sugar: delete an envelope. Equivalent to ENVELOPE DELETE.
func (ns *SigilNamespace) UserDelete(ctx context.Context, schema string, id string) (*SigilUserDeleteResponse, error) {
	args := []string{"USER", "DELETE"}
	args = append(args, schema)
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserGet executes USER GET — Sugar: get an envelope. Equivalent to ENVELOPE GET.
func (ns *SigilNamespace) UserGet(ctx context.Context, schema string, id string) (*SigilUserGetResponse, error) {
	args := []string{"USER", "GET"}
	args = append(args, schema)
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserGetResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserImport executes USER IMPORT — Sugar: import an envelope with pre-hashed credentials. Equivalent to ENVELOPE IMPORT.
func (ns *SigilNamespace) UserImport(ctx context.Context, schema string, id string, jsonData any) (*SigilUserImportResponse, error) {
	args := []string{"USER", "IMPORT"}
	args = append(args, schema)
	args = append(args, id)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserImportResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserLookup executes USER LOOKUP — Sugar: look up by indexed or searchable field value. Equivalent to ENVELOPE LOOKUP.
func (ns *SigilNamespace) UserLookup(ctx context.Context, schema string, field string, value string) (*SigilUserLookupResponse, error) {
	args := []string{"USER", "LOOKUP"}
	args = append(args, schema)
	args = append(args, field)
	args = append(args, value)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserLookupResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserUpdate executes USER UPDATE — Sugar: update non-credential fields. Equivalent to ENVELOPE UPDATE.
func (ns *SigilNamespace) UserUpdate(ctx context.Context, schema string, id string, jsonData any) (*SigilUserUpdateResponse, error) {
	args := []string{"USER", "UPDATE"}
	args = append(args, schema)
	args = append(args, id)
	jsonDataJSON, err := json.Marshal(jsonData)
	if err != nil {
		return nil, fmt.Errorf("marshal json: %w", err)
	}
	args = append(args, string(jsonDataJSON))
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserUpdateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// UserVerify executes USER VERIFY — Sugar: verify credential. Infers the credential field from schema. Equivalent to ENVELOPE VERIFY with implicit field.
func (ns *SigilNamespace) UserVerify(ctx context.Context, schema string, id string, password string) (*SigilUserVerifyResponse, error) {
	args := []string{"USER", "VERIFY"}
	args = append(args, schema)
	args = append(args, id)
	args = append(args, password)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp SigilUserVerifyResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
