// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// StashNamespace provides methods for the stash engine.
//
// Encrypted blob storage with S3 backend and envelope encryption
type StashNamespace struct {
	transport Transport
	engine    string
}

func newStashNamespace(transport Transport, engine string) *StashNamespace {
	return &StashNamespace{transport: transport, engine: engine}
}

// Command executes COMMAND — List supported commands
func (ns *StashNamespace) Command(ctx context.Context) error {
	args := []string{"COMMAND"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Health executes HEALTH — Health check
func (ns *StashNamespace) Health(ctx context.Context) error {
	args := []string{"HEALTH"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Inspect executes INSPECT — Read blob metadata without downloading or decrypting
func (ns *StashNamespace) Inspect(ctx context.Context, id string) (*StashInspectResponse, error) {
	args := []string{"INSPECT"}
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp StashInspectResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Ping-pong
func (ns *StashNamespace) Ping(ctx context.Context) error {
	args := []string{"PING"}
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Retrieve executes RETRIEVE — Retrieve and decrypt a blob
func (ns *StashNamespace) Retrieve(ctx context.Context, id string) error {
	args := []string{"RETRIEVE"}
	args = append(args, id)
	_, err := ns.transport.Execute(ctx, ns.engine, args)
	return err
}

// Revoke executes REVOKE — Revoke a blob (hard crypto-shred by default, SOFT for soft revoke)
func (ns *StashNamespace) Revoke(ctx context.Context, id string, opts *StashRevokeOptions) (*StashRevokeResponse, error) {
	args := []string{"REVOKE"}
	args = append(args, id)
	if opts != nil {
		if opts.Soft {
			args = append(args, "SOFT")
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp StashRevokeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Store executes STORE — Store an encrypted blob
func (ns *StashNamespace) Store(ctx context.Context, id string, data_b64 string, opts *StashStoreOptions) (*StashStoreResponse, error) {
	args := []string{"STORE"}
	args = append(args, id)
	args = append(args, data_b64)
	if opts != nil {
		if opts.ClientEncrypted != nil {
			args = append(args, "CLIENT_ENCRYPTED", fmt.Sprint(*opts.ClientEncrypted))
		}
		if opts.ContentType != nil {
			args = append(args, "CONTENT_TYPE", fmt.Sprint(*opts.ContentType))
		}
		if opts.Keyring != nil {
			args = append(args, "KEYRING", fmt.Sprint(*opts.Keyring))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp StashStoreResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
