// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import "context"

// Transport abstracts the wire protocol used to communicate with ShrouDB
// engines. Implementations handle connection lifecycle and serialization.
type Transport interface {
	// Execute sends a command and returns the parsed response.
	Execute(ctx context.Context, engine string, args []string) (map[string]any, error)

	// Close releases all connections held by this transport.
	Close() error
}
