// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

// ShroudbAuthResponse is the response from shroudb.Auth().
type ShroudbAuthResponse struct {
	Actor string `json:"actor"`
}

// ShroudbCommandListResponse is the response from shroudb.CommandList().
type ShroudbCommandListResponse struct {
	Commands []any `json:"commands"`
	Count int `json:"count"`
}

// ShroudbConfigGetResponse is the response from shroudb.ConfigGet().
type ShroudbConfigGetResponse struct {
	Key string `json:"key"`
	Source any `json:"source"`
	Value any `json:"value"`
}

// ShroudbDeleteResponse is the response from shroudb.Delete().
type ShroudbDeleteResponse struct {
	Version int `json:"version"`
}

// ShroudbGetResponse is the response from shroudb.Get().
type ShroudbGetResponse struct {
	Key any `json:"key"`
	Metadata any `json:"metadata"`
	Value any `json:"value"`
	Version int `json:"version"`
}

// ShroudbHealthResponse is the response from shroudb.Health().
type ShroudbHealthResponse struct {
	Message string `json:"message"`
}

// ShroudbListResponse is the response from shroudb.List().
type ShroudbListResponse struct {
	Cursor any `json:"cursor"`
	Keys []any `json:"keys"`
}

// ShroudbNamespaceInfoResponse is the response from shroudb.NamespaceInfo().
type ShroudbNamespaceInfoResponse struct {
	CreatedAt int `json:"created_at"`
	KeyCount int `json:"key_count"`
	Name string `json:"name"`
}

// ShroudbNamespaceListResponse is the response from shroudb.NamespaceList().
type ShroudbNamespaceListResponse struct {
	Cursor any `json:"cursor"`
	Namespaces []any `json:"namespaces"`
}

// ShroudbNamespaceValidateResponse is the response from shroudb.NamespaceValidate().
type ShroudbNamespaceValidateResponse struct {
	Count int `json:"count"`
	Reports []any `json:"reports"`
}

// ShroudbPingResponse is the response from shroudb.Ping().
type ShroudbPingResponse struct {
	Message string `json:"message"`
}

// ShroudbPutResponse is the response from shroudb.Put().
type ShroudbPutResponse struct {
	Version int `json:"version"`
}

// ShroudbVersionsResponse is the response from shroudb.Versions().
type ShroudbVersionsResponse struct {
	Versions []any `json:"versions"`
}

// ShroudbGetOptions contains optional parameters for shroudb.Get().
type ShroudbGetOptions struct {
	// Version — Specific version number
	Version *int `json:"version,omitempty"`
}

// ShroudbListOptions contains optional parameters for shroudb.List().
type ShroudbListOptions struct {
	Prefix *string `json:"prefix,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	Limit *int `json:"limit,omitempty"`
}

// ShroudbNamespaceAlterOptions contains optional parameters for shroudb.NamespaceAlter().
type ShroudbNamespaceAlterOptions struct {
	Schema any `json:"schema,omitempty"`
	MaxVersions *int `json:"max_versions,omitempty"`
	TombstoneRetention *int `json:"tombstone_retention,omitempty"`
}

// ShroudbNamespaceCreateOptions contains optional parameters for shroudb.NamespaceCreate().
type ShroudbNamespaceCreateOptions struct {
	Schema any `json:"schema,omitempty"`
	MaxVersions *int `json:"max_versions,omitempty"`
	// TombstoneRetention — Seconds to retain tombstones before compaction
	TombstoneRetention *int `json:"tombstone_retention,omitempty"`
}

// ShroudbNamespaceListOptions contains optional parameters for shroudb.NamespaceList().
type ShroudbNamespaceListOptions struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit *int `json:"limit,omitempty"`
}

// ShroudbPutOptions contains optional parameters for shroudb.Put().
type ShroudbPutOptions struct {
	// Meta — JSON metadata object
	Meta any `json:"meta,omitempty"`
}

// ShroudbSubscribeOptions contains optional parameters for shroudb.Subscribe().
type ShroudbSubscribeOptions struct {
	Key *string `json:"key,omitempty"`
	// Events — Event types: PUT, DELETE, or * for all
	Events *any `json:"events,omitempty"`
}

// ShroudbVersionsOptions contains optional parameters for shroudb.Versions().
type ShroudbVersionsOptions struct {
	Limit *int `json:"limit,omitempty"`
	// From — Start from this version number (descending)
	From *int `json:"from,omitempty"`
}

// CipherAuthResponse is the response from cipher.Auth().
type CipherAuthResponse struct {
	// Status — OK on success
	Status string `json:"status"`
}

// CipherCommandListResponse is the response from cipher.CommandList().
type CipherCommandListResponse struct {
	// Count — Number of supported commands
	Count int `json:"count"`
	// Commands — List of command verb strings
	Commands []any `json:"commands"`
}

// CipherDecryptResponse is the response from cipher.Decrypt().
type CipherDecryptResponse struct {
	// Plaintext — Decrypted data
	Plaintext string `json:"plaintext"`
}

// CipherEncryptResponse is the response from cipher.Encrypt().
type CipherEncryptResponse struct {
	// Ciphertext — Encrypted data with embedded key version
	Ciphertext string `json:"ciphertext"`
	// KeyVersion — Key version used for encryption
	KeyVersion int `json:"key_version"`
}

// CipherGenerateDataKeyResponse is the response from cipher.GenerateDataKey().
type CipherGenerateDataKeyResponse struct {
	// PlaintextKey — Plaintext DEK (use for local encryption, then discard)
	PlaintextKey string `json:"plaintext_key"`
	// WrappedKey — Wrapped DEK (store alongside ciphertext, unwrap via DECRYPT)
	WrappedKey string `json:"wrapped_key"`
	// KeyVersion — Key version used to wrap
	KeyVersion int `json:"key_version"`
}

// CipherHealthResponse is the response from cipher.Health().
type CipherHealthResponse struct {
	// Status — ok
	Status string `json:"status"`
}

// CipherKeyInfoResponse is the response from cipher.KeyInfo().
type CipherKeyInfoResponse struct {
	// Keyring — Keyring name
	Keyring string `json:"keyring"`
	// Algorithm — Keyring algorithm
	Algorithm string `json:"algorithm"`
	// ActiveVersion — Currently active key version
	ActiveVersion int `json:"active_version"`
	// Versions — List of all key versions with state
	Versions []any `json:"versions"`
}

// CipherKeyringCreateResponse is the response from cipher.KeyringCreate().
type CipherKeyringCreateResponse struct {
	// Keyring — Keyring name
	Keyring string `json:"keyring"`
	// Algorithm — Algorithm
	Algorithm string `json:"algorithm"`
	// ActiveVersion — Active key version
	ActiveVersion int `json:"active_version"`
}

// CipherKeyringListResponse is the response from cipher.KeyringList().
type CipherKeyringListResponse struct {
	// Keyrings — List of keyring names
	Keyrings []any `json:"keyrings"`
}

// CipherPingResponse is the response from cipher.Ping().
type CipherPingResponse struct {
	// Message — Always PONG
	Message string `json:"message"`
}

// CipherRewrapResponse is the response from cipher.Rewrap().
type CipherRewrapResponse struct {
	// Ciphertext — Re-encrypted ciphertext with new key version
	Ciphertext string `json:"ciphertext"`
	// KeyVersion — New key version used
	KeyVersion int `json:"key_version"`
}

// CipherRotateResponse is the response from cipher.Rotate().
type CipherRotateResponse struct {
	// Rotated — Whether rotation occurred
	Rotated bool `json:"rotated"`
	// KeyVersion — Active key version after operation
	KeyVersion int `json:"key_version"`
	// PreviousVersion — Previous active key version
	PreviousVersion int `json:"previous_version,omitempty"`
}

// CipherSignResponse is the response from cipher.Sign().
type CipherSignResponse struct {
	// Signature — Hex-encoded detached signature
	Signature string `json:"signature"`
	// KeyVersion — Key version used
	KeyVersion int `json:"key_version"`
}

// CipherVerifySignatureResponse is the response from cipher.VerifySignature().
type CipherVerifySignatureResponse struct {
	// Valid — Whether the signature is valid
	Valid bool `json:"valid"`
}

// CipherDecryptOptions contains optional parameters for cipher.Decrypt().
type CipherDecryptOptions struct {
	// Context — AAD used during encryption
	Context *string `json:"context,omitempty"`
}

// CipherEncryptOptions contains optional parameters for cipher.Encrypt().
type CipherEncryptOptions struct {
	// Context — Additional authenticated data (AAD)
	Context *string `json:"context,omitempty"`
	// KeyVersion — Specific key version to use (default: active)
	KeyVersion *int `json:"key_version,omitempty"`
	// Convergent — Opt-in to deterministic encryption (keyring must have convergent=true, CONTEXT required)
	Convergent bool `json:"convergent,omitempty"`
}

// CipherGenerateDataKeyOptions contains optional parameters for cipher.GenerateDataKey().
type CipherGenerateDataKeyOptions struct {
	// Bits — Key size in bits: 128, 256, or 512 (default: 256)
	Bits *int `json:"bits,omitempty"`
}

// CipherKeyringCreateOptions contains optional parameters for cipher.KeyringCreate().
type CipherKeyringCreateOptions struct {
	// RotationDays — Auto-rotation period in days (default: 90)
	RotationDays *int `json:"rotation_days,omitempty"`
	// DrainDays — Drain period before retirement in days (default: 30)
	DrainDays *int `json:"drain_days,omitempty"`
	// Convergent — Enable convergent (deterministic) encryption
	Convergent bool `json:"convergent,omitempty"`
}

// CipherRewrapOptions contains optional parameters for cipher.Rewrap().
type CipherRewrapOptions struct {
	// Context — AAD
	Context *string `json:"context,omitempty"`
}

// CipherRotateOptions contains optional parameters for cipher.Rotate().
type CipherRotateOptions struct {
	// Force — Force rotation regardless of age
	Force bool `json:"force,omitempty"`
	// Dryrun — Preview rotation without applying
	Dryrun bool `json:"dryrun,omitempty"`
}

// SigilCredentialChangeResponse is the response from sigil.CredentialChange().
type SigilCredentialChangeResponse struct {
	Status string `json:"status"`
}

// SigilCredentialImportResponse is the response from sigil.CredentialImport().
type SigilCredentialImportResponse struct {
	Algorithm string `json:"algorithm"`
}

// SigilCredentialResetResponse is the response from sigil.CredentialReset().
type SigilCredentialResetResponse struct {
	Status string `json:"status"`
}

// SigilEnvelopeCreateResponse is the response from sigil.EnvelopeCreate().
type SigilEnvelopeCreateResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	Id string `json:"id"`
}

// SigilEnvelopeDeleteResponse is the response from sigil.EnvelopeDelete().
type SigilEnvelopeDeleteResponse struct {
	Status string `json:"status"`
}

// SigilEnvelopeGetResponse is the response from sigil.EnvelopeGet().
type SigilEnvelopeGetResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	Id string `json:"id"`
	UpdatedAt int `json:"updated_at"`
}

// SigilEnvelopeImportResponse is the response from sigil.EnvelopeImport().
type SigilEnvelopeImportResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	Id string `json:"id"`
}

// SigilEnvelopeLookupResponse is the response from sigil.EnvelopeLookup().
type SigilEnvelopeLookupResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	Id string `json:"id"`
	UpdatedAt int `json:"updated_at"`
}

// SigilEnvelopeUpdateResponse is the response from sigil.EnvelopeUpdate().
type SigilEnvelopeUpdateResponse struct {
	Fields any `json:"fields"`
	Id string `json:"id"`
	UpdatedAt int `json:"updated_at"`
}

// SigilEnvelopeVerifyResponse is the response from sigil.EnvelopeVerify().
type SigilEnvelopeVerifyResponse struct {
	Valid bool `json:"valid"`
}

// SigilHealthResponse is the response from sigil.Health().
type SigilHealthResponse struct {
	Status string `json:"status"`
}

// SigilJwksResponse is the response from sigil.Jwks().
type SigilJwksResponse struct {
	Keys []any `json:"keys"`
}

// SigilPasswordChangeResponse is the response from sigil.PasswordChange().
type SigilPasswordChangeResponse struct {
	Status string `json:"status"`
}

// SigilPasswordImportResponse is the response from sigil.PasswordImport().
type SigilPasswordImportResponse struct {
	Algorithm string `json:"algorithm"`
}

// SigilPasswordResetResponse is the response from sigil.PasswordReset().
type SigilPasswordResetResponse struct {
	Status string `json:"status"`
}

// SigilSchemaGetResponse is the response from sigil.SchemaGet().
type SigilSchemaGetResponse struct {
	Schema any `json:"schema"`
}

// SigilSchemaListResponse is the response from sigil.SchemaList().
type SigilSchemaListResponse struct {
	Names []any `json:"names"`
}

// SigilSchemaRegisterResponse is the response from sigil.SchemaRegister().
type SigilSchemaRegisterResponse struct {
	Version int `json:"version"`
}

// SigilSessionCreateResponse is the response from sigil.SessionCreate().
type SigilSessionCreateResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn int `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
}

// SigilSessionListResponse is the response from sigil.SessionList().
type SigilSessionListResponse struct {
	Sessions []any `json:"sessions"`
}

// SigilSessionRefreshResponse is the response from sigil.SessionRefresh().
type SigilSessionRefreshResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn int `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
}

// SigilSessionRevokeResponse is the response from sigil.SessionRevoke().
type SigilSessionRevokeResponse struct {
	Status string `json:"status"`
}

// SigilSessionRevokeAllResponse is the response from sigil.SessionRevokeAll().
type SigilSessionRevokeAllResponse struct {
	Revoked int `json:"revoked"`
}

// SigilUserCreateResponse is the response from sigil.UserCreate().
type SigilUserCreateResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	UserId string `json:"user_id"`
}

// SigilUserDeleteResponse is the response from sigil.UserDelete().
type SigilUserDeleteResponse struct {
	Status string `json:"status"`
}

// SigilUserGetResponse is the response from sigil.UserGet().
type SigilUserGetResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	UpdatedAt int `json:"updated_at"`
	UserId string `json:"user_id"`
}

// SigilUserImportResponse is the response from sigil.UserImport().
type SigilUserImportResponse struct {
	CreatedAt int `json:"created_at"`
	Fields any `json:"fields"`
	UserId string `json:"user_id"`
}

// SigilUserUpdateResponse is the response from sigil.UserUpdate().
type SigilUserUpdateResponse struct {
	Fields any `json:"fields"`
	UpdatedAt int `json:"updated_at"`
	UserId string `json:"user_id"`
}

// SigilUserVerifyResponse is the response from sigil.UserVerify().
type SigilUserVerifyResponse struct {
	Valid bool `json:"valid"`
}

// SigilCredentialImportOptions contains optional parameters for sigil.CredentialImport().
type SigilCredentialImportOptions struct {
	Meta any `json:"meta,omitempty"`
}

// SigilPasswordImportOptions contains optional parameters for sigil.PasswordImport().
type SigilPasswordImportOptions struct {
	Meta any `json:"meta,omitempty"`
}

// SigilSessionCreateOptions contains optional parameters for sigil.SessionCreate().
type SigilSessionCreateOptions struct {
	// Meta — Extra claims to merge into access token
	Meta any `json:"meta,omitempty"`
}

// VeilAuthResponse is the response from veil.Auth().
type VeilAuthResponse struct {
	Status any `json:"status"`
}

// VeilCommandListResponse is the response from veil.CommandList().
type VeilCommandListResponse struct {
	Count any `json:"count"`
	Commands any `json:"commands"`
}

// VeilDeleteResponse is the response from veil.Delete().
type VeilDeleteResponse struct {
	Status any `json:"status"`
	Id any `json:"id"`
}

// VeilHealthResponse is the response from veil.Health().
type VeilHealthResponse struct {
	Status any `json:"status"`
}

// VeilIndexCreateResponse is the response from veil.IndexCreate().
type VeilIndexCreateResponse struct {
	Status any `json:"status"`
	Index any `json:"index"`
	CreatedAt any `json:"created_at"`
	TokenizerVersion any `json:"tokenizer_version"`
}

// VeilIndexDestroyResponse is the response from veil.IndexDestroy().
type VeilIndexDestroyResponse struct {
	Status any `json:"status"`
	Index any `json:"index"`
	DeletedEntries any `json:"deleted_entries"`
}

// VeilIndexInfoResponse is the response from veil.IndexInfo().
type VeilIndexInfoResponse struct {
	Index any `json:"index"`
	CreatedAt any `json:"created_at"`
	EntryCount any `json:"entry_count"`
	TokenizerVersion any `json:"tokenizer_version"`
}

// VeilIndexListResponse is the response from veil.IndexList().
type VeilIndexListResponse struct {
	Items string `json:"items"`
	Type []any `json:"type"`
}

// VeilIndexReconcileResponse is the response from veil.IndexReconcile().
type VeilIndexReconcileResponse struct {
	Status any `json:"status"`
	Index any `json:"index"`
	OrphansRemoved any `json:"orphans_removed"`
}

// VeilIndexReindexResponse is the response from veil.IndexReindex().
type VeilIndexReindexResponse struct {
	Status any `json:"status"`
	Index any `json:"index"`
	TokenizerVersion any `json:"tokenizer_version"`
	EntriesCleared any `json:"entries_cleared"`
}

// VeilIndexRotateResponse is the response from veil.IndexRotate().
type VeilIndexRotateResponse struct {
	Status any `json:"status"`
	Index any `json:"index"`
	RotatedAt any `json:"rotated_at"`
	EntryCount any `json:"entry_count"`
}

// VeilPingResponse is the response from veil.Ping().
type VeilPingResponse struct {
	Type string `json:"type"`
	Value any `json:"value"`
}

// VeilPutResponse is the response from veil.Put().
type VeilPutResponse struct {
	Status any `json:"status"`
	Id any `json:"id"`
	Version any `json:"version"`
}

// VeilSearchResponse is the response from veil.Search().
type VeilSearchResponse struct {
	Status any `json:"status"`
	Scanned any `json:"scanned"`
	Matched any `json:"matched"`
	Results any `json:"results"`
}

// VeilTokenizeResponse is the response from veil.Tokenize().
type VeilTokenizeResponse struct {
	Status any `json:"status"`
	Words any `json:"words"`
	Trigrams any `json:"trigrams"`
	Tokens any `json:"tokens"`
}

// VeilPutOptions contains optional parameters for veil.Put().
type VeilPutOptions struct {
	// Field — JSON field to extract for tokenization (standard mode only)
	Field *string `json:"field,omitempty"`
	// Blind — E2EE mode: treat data_b64 as pre-computed blind tokens
	Blind bool `json:"blind,omitempty"`
}

// VeilSearchOptions contains optional parameters for veil.Search().
type VeilSearchOptions struct {
	// Mode — Match mode: exact, contains, prefix, fuzzy
	Mode *string `json:"mode,omitempty"`
	// Field — JSON field to extract for tokenization (standard mode only)
	Field *string `json:"field,omitempty"`
	// Limit — Maximum results to return
	Limit *int `json:"limit,omitempty"`
	// Blind — E2EE mode: treat query as pre-computed blind tokens
	Blind bool `json:"blind,omitempty"`
}

// VeilTokenizeOptions contains optional parameters for veil.Tokenize().
type VeilTokenizeOptions struct {
	// Field — JSON field to extract for tokenization
	Field *string `json:"field,omitempty"`
}

// SentryAuthResponse is the response from sentry.Auth().
type SentryAuthResponse struct {
	Status string `json:"status"`
}

// SentryCommandListResponse is the response from sentry.CommandList().
type SentryCommandListResponse struct {
	Commands []any `json:"commands"`
	Status string `json:"status"`
}

// SentryEvaluateResponse is the response from sentry.Evaluate().
type SentryEvaluateResponse struct {
	CacheUntil int `json:"cache_until"`
	Decision string `json:"decision"`
	MatchedPolicy string `json:"matched_policy"`
	Status string `json:"status"`
	Token string `json:"token"`
}

// SentryHealthResponse is the response from sentry.Health().
type SentryHealthResponse struct {
	PolicyCount int `json:"policy_count"`
	Status string `json:"status"`
}

// SentryJwksResponse is the response from sentry.Jwks().
type SentryJwksResponse struct {
	Keys []any `json:"keys"`
}

// SentryKeyInfoResponse is the response from sentry.KeyInfo().
type SentryKeyInfoResponse struct {
	ActiveKid string `json:"active_kid"`
	ActiveVersion int `json:"active_version"`
	Algorithm string `json:"algorithm"`
	DecisionTtlSecs int `json:"decision_ttl_secs"`
	DrainDays int `json:"drain_days"`
	JwksKeys int `json:"jwks_keys"`
	RotationDays int `json:"rotation_days"`
	Status string `json:"status"`
	TotalVersions int `json:"total_versions"`
}

// SentryKeyRotateResponse is the response from sentry.KeyRotate().
type SentryKeyRotateResponse struct {
	KeyVersion int `json:"key_version"`
	PreviousVersion int `json:"previous_version"`
	Rotated bool `json:"rotated"`
	Status string `json:"status"`
}

// SentryPolicyCreateResponse is the response from sentry.PolicyCreate().
type SentryPolicyCreateResponse struct {
	Effect string `json:"effect"`
	Name string `json:"name"`
	Priority int `json:"priority"`
	Status string `json:"status"`
	Version int `json:"version"`
}

// SentryPolicyDeleteResponse is the response from sentry.PolicyDelete().
type SentryPolicyDeleteResponse struct {
	Status string `json:"status"`
}

// SentryPolicyGetResponse is the response from sentry.PolicyGet().
type SentryPolicyGetResponse struct {
	Action any `json:"action"`
	Conditions any `json:"conditions"`
	CreatedAt int `json:"created_at"`
	Description string `json:"description"`
	Effect string `json:"effect"`
	Name string `json:"name"`
	Principal any `json:"principal"`
	Priority int `json:"priority"`
	Resource any `json:"resource"`
	Status string `json:"status"`
	UpdatedAt int `json:"updated_at"`
	Version int `json:"version"`
}

// SentryPolicyHistoryResponse is the response from sentry.PolicyHistory().
type SentryPolicyHistoryResponse struct {
	Count int `json:"count"`
	Name string `json:"name"`
	Status string `json:"status"`
	Versions []any `json:"versions"`
}

// SentryPolicyListResponse is the response from sentry.PolicyList().
type SentryPolicyListResponse struct {
	Count int `json:"count"`
	Policies []any `json:"policies"`
	Status string `json:"status"`
}

// SentryPolicyUpdateResponse is the response from sentry.PolicyUpdate().
type SentryPolicyUpdateResponse struct {
	Effect string `json:"effect"`
	Name string `json:"name"`
	Priority int `json:"priority"`
	Status string `json:"status"`
	UpdatedAt int `json:"updated_at"`
	Version int `json:"version"`
}

// SentryKeyRotateOptions contains optional parameters for sentry.KeyRotate().
type SentryKeyRotateOptions struct {
	// Force — Force rotation regardless of key age
	Force bool `json:"FORCE,omitempty"`
	// Dryrun — Preview rotation without applying
	Dryrun bool `json:"DRYRUN,omitempty"`
}

// ForgeCaCreateResponse is the response from forge.CaCreate().
type ForgeCaCreateResponse struct {
	ActiveVersion int `json:"active_version"`
	Algorithm string `json:"algorithm"`
	Name string `json:"name"`
	Subject string `json:"subject"`
}

// ForgeCaExportResponse is the response from forge.CaExport().
type ForgeCaExportResponse struct {
	CertificatePem string `json:"certificate_pem"`
}

// ForgeCaInfoResponse is the response from forge.CaInfo().
type ForgeCaInfoResponse struct {
	Algorithm string `json:"algorithm"`
	KeyVersions []any `json:"key_versions"`
	Name string `json:"name"`
	Subject string `json:"subject"`
}

// ForgeCaListResponse is the response from forge.CaList().
type ForgeCaListResponse struct {
	Cas []any `json:"cas"`
}

// ForgeCaRotateResponse is the response from forge.CaRotate().
type ForgeCaRotateResponse struct {
	KeyVersion int `json:"key_version"`
	PreviousVersion int `json:"previous_version"`
	Rotated bool `json:"rotated"`
}

// ForgeConfigGetResponse is the response from forge.ConfigGet().
type ForgeConfigGetResponse struct {
	Key string `json:"key"`
	Status string `json:"status"`
	Value any `json:"value"`
}

// ForgeConfigSetResponse is the response from forge.ConfigSet().
type ForgeConfigSetResponse struct {
	Key string `json:"key"`
	Status string `json:"status"`
	Value string `json:"value"`
}

// ForgeInspectResponse is the response from forge.Inspect().
type ForgeInspectResponse struct {
	CertificatePem string `json:"certificate_pem"`
	Serial string `json:"serial"`
	State string `json:"state"`
	Subject string `json:"subject"`
}

// ForgeIssueResponse is the response from forge.Issue().
type ForgeIssueResponse struct {
	CertificatePem string `json:"certificate_pem"`
	PrivateKeyPem string `json:"private_key_pem"`
	Serial string `json:"serial"`
}

// ForgeIssueFromCsrResponse is the response from forge.IssueFromCsr().
type ForgeIssueFromCsrResponse struct {
	CertificatePem string `json:"certificate_pem"`
	Serial string `json:"serial"`
}

// ForgeListCertsResponse is the response from forge.ListCerts().
type ForgeListCertsResponse struct {
	Certs []any `json:"certs"`
	Count int `json:"count"`
}

// ForgeRenewResponse is the response from forge.Renew().
type ForgeRenewResponse struct {
	CertificatePem string `json:"certificate_pem"`
	PrivateKeyPem string `json:"private_key_pem"`
	Serial string `json:"serial"`
}

// ForgeRevokeResponse is the response from forge.Revoke().
type ForgeRevokeResponse struct {
	Status string `json:"status"`
}

// ForgeCaCreateOptions contains optional parameters for forge.CaCreate().
type ForgeCaCreateOptions struct {
	TtlDays *int `json:"ttl_days,omitempty"`
	Parent *string `json:"parent,omitempty"`
}

// ForgeCaRotateOptions contains optional parameters for forge.CaRotate().
type ForgeCaRotateOptions struct {
	Force bool `json:"force,omitempty"`
	Dryrun bool `json:"dryrun,omitempty"`
}

// ForgeIssueOptions contains optional parameters for forge.Issue().
type ForgeIssueOptions struct {
	Ttl *string `json:"ttl,omitempty"`
	SanDns *any `json:"san_dns,omitempty"`
	SanIp *any `json:"san_ip,omitempty"`
}

// ForgeIssueFromCsrOptions contains optional parameters for forge.IssueFromCsr().
type ForgeIssueFromCsrOptions struct {
	Ttl *string `json:"ttl,omitempty"`
}

// ForgeListCertsOptions contains optional parameters for forge.ListCerts().
type ForgeListCertsOptions struct {
	State *string `json:"state,omitempty"`
	Limit *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

// ForgeRenewOptions contains optional parameters for forge.Renew().
type ForgeRenewOptions struct {
	Ttl *string `json:"ttl,omitempty"`
}

// ForgeRevokeOptions contains optional parameters for forge.Revoke().
type ForgeRevokeOptions struct {
	Reason *string `json:"reason,omitempty"`
}

// KeepAuthResponse is the response from keep.Auth().
type KeepAuthResponse struct {
	Status string `json:"status"`
}

// KeepCommandListResponse is the response from keep.CommandList().
type KeepCommandListResponse struct {
	Count int `json:"count"`
	Commands []any `json:"commands"`
}

// KeepDeleteResponse is the response from keep.Delete().
type KeepDeleteResponse struct {
	Status string `json:"status"`
	Path string `json:"path"`
	DeletedAt int `json:"deleted_at"`
}

// KeepGetResponse is the response from keep.Get().
type KeepGetResponse struct {
	Status string `json:"status"`
	Path string `json:"path"`
	Version int `json:"version"`
	Value string `json:"value"`
	CreatedAt int `json:"created_at"`
	CreatedBy string `json:"created_by"`
}

// KeepHealthResponse is the response from keep.Health().
type KeepHealthResponse struct {
	Status string `json:"status"`
}

// KeepListResponse is the response from keep.List().
type KeepListResponse struct {
	Status string `json:"status"`
	Count int `json:"count"`
	Paths []any `json:"paths"`
}

// KeepPurgeResponse is the response from keep.Purge().
type KeepPurgeResponse struct {
	Status string `json:"status"`
	Path string `json:"path"`
	PurgedAt any `json:"purged_at"`
}

// KeepPutResponse is the response from keep.Put().
type KeepPutResponse struct {
	Status string `json:"status"`
	Path string `json:"path"`
	Version int `json:"version"`
}

// KeepRotateResponse is the response from keep.Rotate().
type KeepRotateResponse struct {
	Status string `json:"status"`
	Path string `json:"path"`
	Version int `json:"version"`
}

// KeepVersionsResponse is the response from keep.Versions().
type KeepVersionsResponse struct {
	Status string `json:"status"`
	Path string `json:"path"`
	VersionCount int `json:"version_count"`
	Versions []any `json:"versions"`
	Deleted bool `json:"deleted"`
}

// KeepGetOptions contains optional parameters for keep.Get().
type KeepGetOptions struct {
	Version *int `json:"version,omitempty"`
}

// CourierAuthResponse is the response from courier.Auth().
type CourierAuthResponse struct {
	Status string `json:"status"`
}

// CourierChannelCreateResponse is the response from courier.ChannelCreate().
type CourierChannelCreateResponse struct {
	ChannelType string `json:"channel_type"`
	Name string `json:"name"`
	Status string `json:"status"`
}

// CourierChannelDeleteResponse is the response from courier.ChannelDelete().
type CourierChannelDeleteResponse struct {
	Name string `json:"name"`
	Status string `json:"status"`
}

// CourierChannelGetResponse is the response from courier.ChannelGet().
type CourierChannelGetResponse struct {
	ChannelType string `json:"channel_type"`
	CreatedAt int `json:"created_at"`
	Enabled bool `json:"enabled"`
	Name string `json:"name"`
}

// CourierChannelListResponse is the response from courier.ChannelList().
type CourierChannelListResponse struct {
	Channels []any `json:"channels"`
	Count int `json:"count"`
	Status string `json:"status"`
}

// CourierCommandListResponse is the response from courier.CommandList().
type CourierCommandListResponse struct {
	Commands []any `json:"commands"`
	Count int `json:"count"`
}

// CourierDeliverResponse is the response from courier.Deliver().
type CourierDeliverResponse struct {
	Channel string `json:"channel"`
	DeliveredAt int `json:"delivered_at"`
	DeliveryId string `json:"delivery_id"`
	Status string `json:"status"`
}

// CourierDeliveryGetResponse is the response from courier.DeliveryGet().
type CourierDeliveryGetResponse struct {
	Channel string `json:"channel"`
	DeliveredAt int `json:"delivered_at"`
	DeliveryId string `json:"delivery_id"`
	Error string `json:"error"`
	Status string `json:"status"`
}

// CourierDeliveryListResponse is the response from courier.DeliveryList().
type CourierDeliveryListResponse struct {
	Count int `json:"count"`
	Receipts []any `json:"receipts"`
	Status string `json:"status"`
}

// CourierHealthResponse is the response from courier.Health().
type CourierHealthResponse struct {
	Channels int `json:"channels"`
	Status string `json:"status"`
}

// CourierMetricsResponse is the response from courier.Metrics().
type CourierMetricsResponse struct {
	Delivered int `json:"delivered"`
	Failed int `json:"failed"`
	PerChannel any `json:"per_channel"`
	TotalDeliveries int `json:"total_deliveries"`
}

// CourierNotifyEventResponse is the response from courier.NotifyEvent().
type CourierNotifyEventResponse struct {
	Channel string `json:"channel"`
	DeliveredAt int `json:"delivered_at"`
	DeliveryId string `json:"delivery_id"`
	Status string `json:"status"`
}

// CourierDeliveryListOptions contains optional parameters for courier.DeliveryList().
type CourierDeliveryListOptions struct {
	// Channel — Filter by channel name
	Channel *string `json:"CHANNEL,omitempty"`
	// Limit — Max receipts to return (default 100)
	Limit *int `json:"LIMIT,omitempty"`
}

// ChronicleActorsResponse is the response from chronicle.Actors().
type ChronicleActorsResponse struct {
	Entries []any `json:"entries"`
}

// ChronicleAuthResponse is the response from chronicle.Auth().
type ChronicleAuthResponse struct {
	Status string `json:"status"`
}

// ChronicleCountResponse is the response from chronicle.Count().
type ChronicleCountResponse struct {
	Count int `json:"count"`
}

// ChronicleErrorsResponse is the response from chronicle.Errors().
type ChronicleErrorsResponse struct {
	Entries []any `json:"entries"`
}

// ChronicleHealthResponse is the response from chronicle.Health().
type ChronicleHealthResponse struct {
	Status string `json:"status"`
}

// ChronicleHotspotsResponse is the response from chronicle.Hotspots().
type ChronicleHotspotsResponse struct {
	Entries []any `json:"entries"`
}

// ChronicleIngestResponse is the response from chronicle.Ingest().
type ChronicleIngestResponse struct {
	Status string `json:"status"`
}

// ChronicleIngestBatchResponse is the response from chronicle.IngestBatch().
type ChronicleIngestBatchResponse struct {
	Ingested int `json:"ingested"`
	Status string `json:"status"`
}

// ChronicleQueryResponse is the response from chronicle.Query().
type ChronicleQueryResponse struct {
	Events []any `json:"events"`
}

// ChronicleVerifyResponse is the response from chronicle.Verify().
type ChronicleVerifyResponse struct {
	Status string `json:"status"`
	Total int `json:"total"`
	Verified int `json:"verified"`
}

// ChronicleActorsOptions contains optional parameters for chronicle.Actors().
type ChronicleActorsOptions struct {
	FilterArgs *any `json:"filter_args,omitempty"`
}

// ChronicleCountOptions contains optional parameters for chronicle.Count().
type ChronicleCountOptions struct {
	FilterArgs *any `json:"filter_args,omitempty"`
}

// ChronicleErrorsOptions contains optional parameters for chronicle.Errors().
type ChronicleErrorsOptions struct {
	FilterArgs *any `json:"filter_args,omitempty"`
}

// ChronicleHotspotsOptions contains optional parameters for chronicle.Hotspots().
type ChronicleHotspotsOptions struct {
	FilterArgs *any `json:"filter_args,omitempty"`
}

// ChronicleQueryOptions contains optional parameters for chronicle.Query().
type ChronicleQueryOptions struct {
	// FilterArgs — Filter predicates
	FilterArgs *any `json:"filter_args,omitempty"`
}

// StashInspectResponse is the response from stash.Inspect().
type StashInspectResponse struct {
	BlobStatus string `json:"blob_status"`
	ClientEncrypted bool `json:"client_encrypted"`
	ContentType string `json:"content_type"`
	CreatedAt int `json:"created_at"`
	EncryptedSize int `json:"encrypted_size"`
	Id string `json:"id"`
	KeyVersion int `json:"key_version"`
	Keyring string `json:"keyring"`
	PlaintextSize int `json:"plaintext_size"`
	Status string `json:"status"`
	UpdatedAt int `json:"updated_at"`
	ViewerCount int `json:"viewer_count"`
}

// StashRevokeResponse is the response from stash.Revoke().
type StashRevokeResponse struct {
	Id string `json:"id"`
	RevokeMode string `json:"revoke_mode"`
	Status string `json:"status"`
}

// StashRewrapResponse is the response from stash.Rewrap().
type StashRewrapResponse struct {
	Id string `json:"id"`
	KeyVersion int `json:"key_version"`
	Status string `json:"status"`
	UpdatedAt int `json:"updated_at"`
}

// StashStoreResponse is the response from stash.Store().
type StashStoreResponse struct {
	ClientEncrypted bool `json:"client_encrypted"`
	EncryptedSize int `json:"encrypted_size"`
	Id string `json:"id"`
	KeyVersion int `json:"key_version"`
	Keyring string `json:"keyring"`
	PlaintextSize int `json:"plaintext_size"`
	S3Key string `json:"s3_key"`
	Status string `json:"status"`
}

// StashRevokeOptions contains optional parameters for stash.Revoke().
type StashRevokeOptions struct {
	// Soft — Soft revoke (preserve data, block access)
	Soft bool `json:"soft,omitempty"`
}

// StashStoreOptions contains optional parameters for stash.Store().
type StashStoreOptions struct {
	// ClientEncrypted — Passthrough mode: value is the wrapped DEK from client-side encryption
	ClientEncrypted *string `json:"client_encrypted,omitempty"`
	// ContentType — MIME content type
	ContentType *string `json:"content_type,omitempty"`
	// Keyring — Cipher keyring name (default: stash-blobs)
	Keyring *string `json:"keyring,omitempty"`
}
