// Auto-generated by shroudb-codegen. Do not edit.

package shroudb

import (
	"context"
	"encoding/json"
	"fmt"
)

// VeilNamespace provides methods for the veil engine.
//
// veil
type VeilNamespace struct {
	transport Transport
	engine    string
}

func newVeilNamespace(transport Transport, engine string) *VeilNamespace {
	return &VeilNamespace{transport: transport, engine: engine}
}

// Auth executes AUTH — Authenticate this connection
func (ns *VeilNamespace) Auth(ctx context.Context, token string) (*VeilAuthResponse, error) {
	args := []string{"AUTH"}
	args = append(args, token)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilAuthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// CommandList executes COMMAND LIST — List all supported commands
func (ns *VeilNamespace) CommandList(ctx context.Context) (*VeilCommandListResponse, error) {
	args := []string{"COMMAND", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilCommandListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Delete executes DELETE — Remove an entry's blind tokens from the index
func (ns *VeilNamespace) Delete(ctx context.Context, index string, id string) (*VeilDeleteResponse, error) {
	args := []string{"DELETE"}
	args = append(args, index)
	args = append(args, id)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilDeleteResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Health executes HEALTH — Health check
func (ns *VeilNamespace) Health(ctx context.Context) (*VeilHealthResponse, error) {
	args := []string{"HEALTH"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilHealthResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// IndexCreate executes INDEX CREATE — Create a new blind index with a fresh HMAC key
func (ns *VeilNamespace) IndexCreate(ctx context.Context, name string) (*VeilIndexCreateResponse, error) {
	args := []string{"INDEX", "CREATE"}
	args = append(args, name)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilIndexCreateResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// IndexInfo executes INDEX INFO — Get information about a blind index
func (ns *VeilNamespace) IndexInfo(ctx context.Context, name string) (*VeilIndexInfoResponse, error) {
	args := []string{"INDEX", "INFO"}
	args = append(args, name)
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilIndexInfoResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// IndexList executes INDEX LIST — List all blind index names
func (ns *VeilNamespace) IndexList(ctx context.Context) (*VeilIndexListResponse, error) {
	args := []string{"INDEX", "LIST"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilIndexListResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Ping executes PING — Ping-pong
func (ns *VeilNamespace) Ping(ctx context.Context) (*VeilPingResponse, error) {
	args := []string{"PING"}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilPingResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Put executes PUT — Store blind tokens for an entry. In standard mode, data_b64 is base64-encoded plaintext (server tokenizes). With BLIND flag, data_b64 is base64-encoded BlindTokenSet JSON (client pre-tokenized, for E2EE).
func (ns *VeilNamespace) Put(ctx context.Context, index string, id string, data_b64 string, opts *VeilPutOptions) (*VeilPutResponse, error) {
	args := []string{"PUT"}
	args = append(args, index)
	args = append(args, id)
	args = append(args, data_b64)
	if opts != nil {
		if opts.Field != nil {
			args = append(args, "FIELD", fmt.Sprint(*opts.Field))
		}
		if opts.Blind != nil {
			args = append(args, "BLIND", fmt.Sprint(*opts.Blind))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilPutResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Search executes SEARCH — Search a blind index. In standard mode, query is plain text (server tokenizes). With BLIND flag, query is base64-encoded BlindTokenSet JSON (client pre-tokenized, for E2EE).
func (ns *VeilNamespace) Search(ctx context.Context, index string, query string, opts *VeilSearchOptions) (*VeilSearchResponse, error) {
	args := []string{"SEARCH"}
	args = append(args, index)
	args = append(args, query)
	if opts != nil {
		if opts.Mode != nil {
			args = append(args, "MODE", fmt.Sprint(*opts.Mode))
		}
		if opts.Field != nil {
			args = append(args, "FIELD", fmt.Sprint(*opts.Field))
		}
		if opts.Limit != nil {
			args = append(args, "LIMIT", fmt.Sprint(*opts.Limit))
		}
		if opts.Blind != nil {
			args = append(args, "BLIND", fmt.Sprint(*opts.Blind))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilSearchResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}

// Tokenize executes TOKENIZE — Generate blind tokens from plaintext without storing. Returns HMAC-derived tokens for external use.
func (ns *VeilNamespace) Tokenize(ctx context.Context, index string, plaintext_b64 string, opts *VeilTokenizeOptions) (*VeilTokenizeResponse, error) {
	args := []string{"TOKENIZE"}
	args = append(args, index)
	args = append(args, plaintext_b64)
	if opts != nil {
		if opts.Field != nil {
			args = append(args, "FIELD", fmt.Sprint(*opts.Field))
		}
	}
	raw, err := ns.transport.Execute(ctx, ns.engine, args)
	if err != nil {
		return nil, err
	}
	var resp VeilTokenizeResponse
	jsonBytes, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal response: %w", err)
	}
	if err := json.Unmarshal(jsonBytes, &resp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}
	return &resp, nil
}
